var M=M||{};M.Version="1.4";var m_require=m_require||function(){},YES=true,NO=false;M.LOCAL_STORAGE_PREFIX="#m#";M.LOCAL_STORAGE_SUFFIX="_";M.META_CREATED_AT="_createdAt";M.META_UPDATED_AT="_updatedAt";M.META_M_ID="_m_id";
if(localStorage)Object.getPrototypeOf(localStorage).clear=function(a){var b=this.length;if(a==="f"){b=this.length;for(a=b-1;a>=0;a--)this.removeItem(this.key(a))}else for(a=b-1;a>=0;a--){b=this.key(a);RegExp("^"+M.LOCAL_STORAGE_PREFIX+M.Application.name+M.LOCAL_STORAGE_SUFFIX).exec(b)&&this.removeItem(b)}};m_require("core/foundation/m.js");
M.Object={type:"M.Object",create:function(a){var b=function(){};b.prototype=a;return new b},include:function(a){for(var b in a)this[b]=a[b]},extend:function(a){var b=M.Object.create(this);b.include(a);return b},bindToCaller:function(a,b,c){return function(){if(_.isArray(c))return b.apply(a,c);return b.call(a,c)}},get:function(a){return this[a]},set:function(a,b){this[a]=b},destroy:function(){if(this.id&&$("#"+this.id)){var a=this.getChildViewsAsArray(),b;for(b in a)this[a[b]]&&this[a[b]].destroy();
M.EventDispatcher.unregisterEvents(this);M.ViewManager.unregister(this);$("#"+this.id).remove()}delete this},detachContentBinding:function(){this.contentBinding&&this.contentBinding.target&&this.contentBinding.target.observable&&this.contentBinding.property&&this.contentBinding.target.observable.detach(this.contentBinding.property);this.valueBinding&&this.valueBinding.target&&this.valueBinding.target.observable&&this.valueBinding.property&&this.valueBinding.target.observable.detach(this.valueBinding.property)}};
m_require("core/foundation/object.js");
M.Request=M.Object.extend({type:"M.Request",method:"GET",url:null,isAsync:YES,isJSON:NO,timeout:null,callbacks:null,sendNoCacheHeader:YES,sendTimestamp:NO,data:null,request:null,init:function(a){a=a?a:{};return this.extend({method:a.method?a.method:this.method,url:a.url?a.url:this.url,isAsync:a.isAsync!==undefined&&a.isAsync!==null?a.isAsync:this.isAsync,isJSON:a.isJSON!==undefined&&a.isJSON!==null?a.isJSON:this.isJSON,timeout:a.timeout?a.timeout:this.timeout,data:a.data?a.data:this.data,callbacks:a.callbacks,
sendNoCacheHeader:a.sendNoCacheHeader,sendTimestamp:a.sendTimestamp,beforeSend:a.beforeSend?a.beforeSend:this.beforeSend,onError:a.onError?a.onError:this.onError,onSuccess:a.onSuccess?a.onSuccess:this.onSuccess})},beforeSend:function(){},onError:function(){},onSuccess:function(){},internalBeforeSend:function(a){this.sendNoCacheHeader&&a.setRequestHeader("Cache-Control","no-cache");!this.callbacks&&this.beforeSend&&this.beforeSend(a);this.callbacks&&this.callbacks.beforeSend&&M.EventDispatcher.checkHandler(this.callbacks.beforeSend)&&
M.EventDispatcher.callHandler(this.callbacks.beforeSend,null,NO,[a])},internalOnError:function(a,b){!this.callbacks&&this.onError&&this.onError(a,b);this.callbacks&&this.callbacks.error&&M.EventDispatcher.checkHandler(this.callbacks.error)&&M.EventDispatcher.callHandler(this.callbacks.error,null,NO,[a,b])},internalOnSuccess:function(a,b,c){!this.callbacks&&this.onSuccess&&this.onSuccess(a,b,c);this.callbacks&&this.callbacks.success&&M.EventDispatcher.checkHandler(this.callbacks.success)&&M.EventDispatcher.callHandler(this.callbacks.success,
null,NO,[a,b,c])},send:function(){this.request=$.ajax({type:this.method,url:this.url,async:this.isAsync,dataType:this.isJSON?"json":"text",contentType:this.isJSON?"application/json":"application/x-www-form-urlencoded",timeout:this.timeout,data:this.data?this.data:"",context:this,beforeSend:this.internalBeforeSend,success:this.internalOnSuccess,error:this.internalOnError,cache:!this.sendTimestamp})},abort:function(){if(this.request){this.request.abort();return YES}return NO}});m_require("core/foundation/object.js");
M.DeviceSwitch=M.Object.extend({type:"M.DeviceSwitch",device:null,s:function(a){return this.specialize(a)},specialize:function(a){if(!this.device){M.Logger.log("No device specified!",M.ERR);return null}if(this[this.device]&&this[this.device][a])return this[this.device][a];else{M.Logger.log("Key '"+a+"' not defined for device '"+this.device+"'.",M.WARN);return null}}});M.DS=M.DeviceSwitch;m_require("core/foundation/object.js");M.OFFLINE="offline";M.ONLINE="online";M.PORTRAIT_TOP=0;
M.PORTRAIT_BOTTOM=180;M.LANDSCAPE_RIGHT=-90;M.LANDSCAPE_LEFT=90;
M.Environment=M.Object.extend({type:"M.Environment",modernizr:{inputtypes:function(a){for(var b=document.documentElement,c={},d=document.createElement("input"),e=0,f,g,h=a.length;e<h;e++){d.setAttribute("type",g=a[e]);if(f=d.type!=="text"){d.value=":)";d.style.cssText="position:absolute;visibility:hidden;";if(/^range$/.test(g)&&d.style.WebkitAppearance!==undefined){b.appendChild(d);f=document.defaultView;f=f.getComputedStyle&&f.getComputedStyle(d,null).WebkitAppearance!=="textfield"&&d.offsetHeight!==
0;b.removeChild(d)}else if(!/^(search|tel)$/.test(g))if(/^(url|email)$/.test(g))f=d.checkValidity&&d.checkValidity()===false;else if(/^color$/.test(g)){b.appendChild(d);f=d.value!=":)";b.removeChild(d)}else f=d.value!=":)"}c[a[e]]=!!f}return c}("search tel url email datetime date month week time datetime-local number range color".split(" ")),inputattributes:function(a){for(var b={},c=document.createElement("input"),d=0,e=a.length;d<e;d++)b[a[d]]=!!(a[d]in c);if(b.list)b.list=!!(document.createElement("datalist")&&
window.HTMLDataListElement);return b}("autocomplete autofocus list placeholder max min multiple pattern required step".split(" "))},getConnectionStatus:function(a,b){b=b?b:"http://www.google.de/images/logos/ps_logo2.png";var c=this,d=M.ImageView.design({value:b,events:{load:{action:function(e){M.ViewManager.getViewById(e).destroy();a&&M.EventDispatcher.checkHandler(a,"online")&&c.bindToCaller(a.target,a.action,M.ONLINE)()}},error:{action:function(e){M.ViewManager.getViewById(e).destroy();a&&M.EventDispatcher.checkHandler(a,
"offline")&&c.bindToCaller(a.target,a.action,M.OFFLINE)()}}}});$("body").append(d.render());d.registerEvents()},getUserAgent:function(){return navigator.userAgent},getPlatform:function(){return navigator.platform},getSize:function(){var a,b;if(typeof window.innerWidth!="undefined"){a=window.innerWidth;b=window.innerHeight}else if(typeof document.documentElement!="undefined"&&typeof document.documentElement.clientWidth!="undefined"&&document.documentElement.clientWidth!=0){a=document.documentElement.clientWidth;
b=document.documentElement.clientHeight}else{a=document.getElementsByTagName("body")[0].clientWidth;b=document.getElementsByTagName("body")[0].clientHeight}return[a,b]},getWidth:function(){return this.getSize()[0]},getHeight:function(){return this.getSize()[1]},getTotalSize:function(){return[this.getTotalWidth(),this.getTotalHeight()]},getTotalWidth:function(){return $(document).width()},getTotalHeight:function(){return $(document).height()},getOrientation:function(){switch(window.orientation){case 0:return M.PORTRAIT_TOP;
case false:return M.PORTRAIT_BOTTOM;case 90:return M.LANDSCAPE_LEFT;case -90:return M.LANDSCAPE_RIGHT;default:M.Logger.log("This device does not support orientation detection.",M.WARN);return NO}},supportsInputType:function(a){if(this.modernizr.inputtypes&&this.modernizr.inputtypes[a]===YES)return YES;return NO}});m_require("core/foundation/object.js");M.MILLISECONDS="milliseconds";M.SECONDS="seconds";M.MINUTES="minutes";M.HOURS="hours";M.DAYS="days";
M.DAY_NAMES=["Sun","Mon","Tue","Wed","Thu","Fri","Sat","Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"];M.MONTH_NAMES=["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec","January","February","March","April","May","June","July","August","September","October","November","December"];
M.Date=M.Object.extend({type:"M.Date",date:null,now:function(){return this.extend({date:new Date})},tomorrow:function(){return this.daysFromNow(1)},yesterday:function(){return this.daysFromNow(-1)},create:function(a){var b=typeof a==="number"?a:null;if(!b){if((b=/(\d{1,2})\.(\d{1,2})\.(\d{2,4})/.exec(a))&&b[1]&&b[2]&&b[3]){a=$.trim(a).split(" ");a=b[2]+"/"+b[1]+"/"+b[3]+(a[1]?" "+a[1]:"")}b=Date.parse(a)}if(a&&!b){M.Logger.log("Invalid dateString '"+a+"'.",M.WARN);return null}else if(!a)return this.now();
return this.extend({date:new Date(b)})},format:function(a,b){isNaN(this.date)&&M.Logger.log("Invalid date!",M.WARN);var c=/\b(?:[PMCEA][SDP]T|(?:Pacific|Mountain|Central|Eastern|Atlantic) (?:Standard|Daylight|Prevailing) Time|(?:GMT|UTC)(?:[-+]\d{4})?)\b/g,d=/[^-+\dA-Z]/g,e=function(l,q){l=String(l);for(q=q||2;l.length<q;)l="0"+l;return l};if(arguments.length==1&&Object.prototype.toString.call(this.date)=="[object String]"&&!/\d/.test(this.date)){a=this.date;date=undefined}var f=b?"getUTC":"get",
g=this.date[f+"Date"](),h=this.date[f+"Day"](),i=this.date[f+"Month"](),j=this.date[f+"FullYear"](),k=this.date[f+"Hours"](),n=this.date[f+"Minutes"](),p=this.date[f+"Seconds"]();f=this.date[f+"Milliseconds"]();var o=b?0:this.date.getTimezoneOffset(),m={d:g,dd:e(g),ddd:M.DAY_NAMES[h],dddd:M.DAY_NAMES[h+7],D:h,m:i+1,mm:e(i+1),mmm:M.MONTH_NAMES[i],mmmm:M.MONTH_NAMES[i+12],yy:String(j).slice(2),yyyy:j,h:k%12||12,hh:e(k%12||12),H:k,HH:e(k),M:n,MM:e(n),s:p,ss:e(p),l:e(f,3),L:e(f>99?Math.round(f/10):f),
t:k<12?"a":"p",tt:k<12?"am":"pm",T:k<12?"A":"P",TT:k<12?"AM":"PM",Z:b?"UTC":(String(this.date).match(c)||[""]).pop().replace(d,""),o:(o>0?"-":"+")+e(Math.floor(Math.abs(o)/60)*100+Math.abs(o)%60,4),S:["th","st","nd","rd"][g%10>3?0:(g%100-g%10!=10)*g%10]};return a.replace(/d{1,4}|D{1}|m{1,4}|yy(?:yy)?|([HhMsTt])\1?|[LloSZ]|"[^"]*"|'[^']*'/g,function(l){return l in m?m[l]:l.slice(1,l.length-1)})},getTimestamp:function(){if(this.date)return this.date.getTime();return null},daysFromNow:function(a){return this.now().daysFromDate(a)},
daysFromDate:function(a){return this.millisecondsFromDate(a*24*60*60*1E3)},hoursFromNow:function(a){return this.now().hoursFromDate(a)},hoursFromDate:function(a){return this.millisecondsFromDate(a*60*60*1E3)},minutesFromNow:function(a){return this.now().minutesFromDate(a)},minutesFromDate:function(a){return this.millisecondsFromDate(a*60*1E3)},secondsFromNow:function(a){return this.now().secondsFromDate(a)},secondsFromDate:function(a){return this.millisecondsFromDate(a*1E3)},millisecondsFromNow:function(a){return this.now().millisecondsFromDate(a)},
millisecondsFromDate:function(a){this.date||M.Logger.log("no date specified!",M.ERR);return this.extend({date:new Date(this.getTimestamp()+a)})},timeBetween:function(a,b){var c=this.date?this.getTimestamp():null,d=a.date?a.getTimestamp():null;if(c&&d)switch(b){case M.DAYS:return(d-c)/864E5;case M.HOURS:return(d-c)/36E5;case M.MINUTES:return(d-c)/6E4;case M.SECONDS:return(d-c)/1E3;default:return d-c}else c?M.Logger.log("invalid date passed.",M.ERR):M.Logger.log("invalid date.",M.ERR)},getCalendarWeek:function(a,
b,c){if(a)b+=1;else{a=parseIntRadixTen(this.format("yyyy"));b=parseIntRadixTen(this.format("m"));c=parseIntRadixTen(this.format("d"))}var d=Math.floor((14-b)/12);a=a+4800-d;b=c+Math.floor((153*(b+12*d-3)+2)/5)+365*a+Math.floor(a/4)-Math.floor(a/100)+Math.floor(a/400)-32045;b=(b+31741-b%7)%146097%36524%1461;c=Math.floor(b/1460);return Math.floor(((b-c)%365+c)/7)+1},getDatesOfCalendarWeek:function(a,b,c){c=c&&!isNaN(c)?c:this.date?this.format("yyyy"):M.Date.now().format("yyyy");c=M.Date.create("01/01/"+
c);var d=c.format("D"),e=null;e=b?d==1?c:c.daysFromDate(8-(d==0?7:d)):d==0?c:c.daysFromDate(7-d);a=a?a:this.getCalendarWeek();a=e.daysFromDate((a-1)*7);b=[];for(c=0;c<7;c++){d=a.daysFromDate(c);d=M.Date.create(d.format("mm")+"/"+d.format("dd")+"/"+d.format("yyyy"));b.push(d)}return b},getDateByWeekdayAndCalendarWeek:function(a,b,c){if(a&&!isNaN(a)&&(b&&!isNaN(b)||b===0))if((c=M.Date.getDatesOfCalendarWeek(a,NO,c))&&c.length>0&&c[b])return c[b];else M.Logger.log("Day "+b+" of calendar week "+a+" could not be found!",
M.ERR);else M.Logger.log("Please pass a valid calendarWeek and a valid day of the week!",M.ERR)},toJSON:function(){return String(this.date)}});m_require("core/foundation/object.js");
M.I18N=M.Object.extend({type:"M.I18N",defaultLanguage:"en_us",languageMapper:{de:"de_de",en:"en_us"},l:function(a,b){return this.localize(a,b)},localize:function(a,b){var c;if(!M.Application.currentLanguage)M.Application.currentLanguage=this.getLanguage();if(this[M.Application.currentLanguage]&&this[M.Application.currentLanguage][a])c=this[M.Application.currentLanguage][a];else if(this[M.Application.defaultLanguage]&&this[M.Application.defaultLanguage][a]){M.Logger.log("Key '"+a+"' not defined for language '"+
M.Application.currentLanguage+"', switched to default language '"+M.Application.defaultLanguage+"'",M.WARN);c=this[M.Application.defaultLanguage][a]}else if(this[this.defaultLanguage]&&this[this.defaultLanguage][a]){M.Logger.log("Key '"+a+"' not defined for language '"+M.Application.currentLanguage+"', switched to system's default language '"+this.defaultLanguage+"'",M.WARN);c=this[this.defaultLanguage][a]}else{M.Logger.log("Key '"+a+"' not defined for both language '"+M.Application.currentLanguage+
"' and the system's default language '"+this.defaultLanguage+"'",M.WARN);return null}if(b)try{c=_.template(c,b)}catch(d){M.Logger.log('Error in I18N: Check your context object and the translation string with key "'+a+'". Error Message: '+d,M.ERR)}return c},setLanguage:function(a){if(this.isLanguageAvailable(a))if(a&&a===M.Application.currentLanguage)M.Logger.log("Language '"+a+"' already selected",M.INFO);else{if(localStorage){localStorage.setItem(M.LOCAL_STORAGE_PREFIX+M.Application.name+M.LOCAL_STORAGE_SUFFIX+
"lang",a);location.href=location.protocol+"//"+location.host+location.pathname}}else{M.Logger.log("There is no language '"+a+"' specified (using default language '"+this.defaultLanguage+"' instead!",M.WARN);this.setLanguage(this.defaultLanguage)}},getLanguage:function(){var a=null;if(localStorage)a=localStorage.getItem(M.LOCAL_STORAGE_PREFIX+M.Application.name+M.LOCAL_STORAGE_SUFFIX+"lang");if(a)return a;else if(navigator)if((a=/([a-zA-Z]{2,3})[\s_.-]?([a-zA-Z]{2,3})?/.exec(navigator.language))&&
this[a[0]])return a[0].toLowerCase();else if(a&&a[1]&&this.languageMapper[a[1]]){a=this.languageMapper[a[1]];return a.toLowerCase()}else return M.Application.defaultLanguage?M.Application.defaultLanguage.toLowerCase():this.defaultLanguage;else return this.defaultLanguage},isLanguageAvailable:function(a){if(this[a]&&typeof this[a]==="object")return true;else{M.Logger.log("no language '"+a+"' specified.",M.WARN);return false}}});m_require("core/foundation/object.js");
M.ImagePreloader=M.Object.extend({type:"M.ImagePreloader",images:null,refId:"",bodyDOM:null,loadCounter:0,init:function(a){a.refId=a.refId||M.UniqueId.uuid();a.bodyDOM=$("body");return this.extend(a)},preload:function(){var a=this;this.images&&this.images.length>0&&_.each(this.images,function(b){window.setTimeout(function(){a.preloadSingleImage(b)},1)})},preloadSingleImage:function(a){a=M.ImageView.design({value:a,cssClass:"tmp-image-preloading",events:{load:{target:this,action:"loadSingle"},error:{target:this,
action:"error"}}});this.bodyDOM.append(a.render());a.registerEvents()},loadSingle:function(a){this.loadCounter++;a=M.ViewManager.getViewById(a);var b=a.value;a.destroy();this.events&&M.EventDispatcher.checkHandler(this.events.load)&&M.EventDispatcher.callHandler(this.events.load,null,NO,[b,this.refId]);this.loadCounter===this.images.length&&this.finish()},error:function(a){this.loadCounter++;a=M.ViewManager.getViewById(a);var b=a.value;a.destroy();this.events&&M.EventDispatcher.checkHandler(this.events.error)&&
M.EventDispatcher.callHandler(this.events.error,null,NO,[b,this.refId]);this.loadCounter===this.images.length&&this.finish()},finish:function(){this.loadCounter===this.images.length&&this.events&&M.EventDispatcher.checkHandler(this.events.finish)&&M.EventDispatcher.callHandler(this.events.finish,null,NO,[this.refId])}});m_require("core/foundation/object.js");
M.Location=M.Object.extend({type:"M.Location",latitude:null,longitude:null,date:null,accuracy:null,caller:null,onUpdateSuccess:null,onUpdateError:null,init:function(a,b){return this.extend({latitude:a,longitude:b})},update:function(a,b,c,d){this.caller=a;this.onUpdateSuccess=b;this.onUpdateError=c;M.LocationManager.getLocation(this,this.onUpdateSuccessInternal,this.onUpdateErrorInternal,d)},onUpdateSuccessInternal:function(a){if(a&&a.coords){this.latitude=a.coords.latitude;this.longitude=a.coords.longitude;
this.date=M.Date.now();if(this.caller)this.onUpdateSuccess?this.bindToCaller(this.caller,this.onUpdateSuccess)():M.Logger.log("No success callback specified for update() of M.Location.",M.INFO);else M.Logger.log("No caller specified for update() of M.Location.",M.WARN)}else M.Logger.log("An internal error occured while retrieving the position.",M.ERR)},onUpdateErrorInternal:function(a){if(this.caller)this.onUpdateError?this.bindToCaller(this.caller,this.onUpdateError,a)():M.Logger.log("No error callback specified for update() of M.Location.",
M.INFO);else M.Logger.log("No caller specified for update() of M.Location.",M.WARN)}});m_require("core/foundation/object.js");M.FLOOR="floor";M.CEIL="ceil";M.ROUND="round";
M.Math=M.Object.extend({type:"M.Math",pow:function(a,b){return Math.pow(a,b)},random:function(a,b){return Math.ceil(Math.random()*(b-a+1)+a-1)},round:function(a,b,c){if(c)a*=Math.pow(10,c);var d=0;switch(b){case M.FLOOR:d=Math.floor(a);break;case M.CEIL:d=Math.ceil(a);break;default:d=Math.round(a)}if(c){a=String(d/Math.pow(10,c)).split(".");d=a.length>1?parseFloat(a[0]+"."+a[1].substring(0,c)):parseFloat(a)}return d},nearestNumber:function(a,b){var c=null,d=null;_.each(a,function(e){var f=Math.abs(e-
b);if(f<c||!c&&c!==0){c=f;d=e}});return d}});m_require("core/foundation/object.js");M.StringBuilder=M.Object.extend({type:"M.StringBuilder",strings:null,append:function(a,b){b=typeof b==="number"?b:1;if(a){for(var c=1;c<=b;c++)this.strings.push(a);return YES}},clear:function(){this.strings.length=0},toString:function(){return this.strings.join("")},create:function(a){var b=this.extend({strings:[]});b.append(a);return b}});m_require("core/foundation/object.js");
M.UniqueId=M.Object.extend({uuid:function(a,b){var c="0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".split(""),d=[];b=b||c.length;var e;if(a)for(e=0;e<a;e++)d[e]=c[0|Math.random()*b];else{var f;d[8]=d[13]=d[18]=d[23]="-";d[14]="4";for(e=0;e<36;e++)if(!d[e]){f=0|Math.random()*16;d[e]=c[e==19?f&3|8:f]}}return d.join("")}});m_require("core/foundation/object.js");
M.Base64=M.Object.extend({type:"M.Base64",keyString:"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=",encode:function(a){var b="",c,d,e,f,g,h,i=0;for(a=M.Cypher.utf8_encode(a);i<a.length;){c=a.charCodeAt(i++);d=a.charCodeAt(i++);e=a.charCodeAt(i++);f=c>>2;c=(c&3)<<4|d>>4;g=(d&15)<<2|e>>6;h=e&63;if(isNaN(d))g=h=64;else if(isNaN(e))h=64;b+=this.keyString.charAt(f)+this.keyString.charAt(c)+this.keyString.charAt(g)+this.keyString.charAt(h)}return b},decode:function(a){var b="",c,d,e,
f,g,h=0;for(a=a.replace(/[^A-Za-z0-9\+\/\=]/g,"");h<a.length;){c=this.keyString.indexOf(a.charAt(h++));d=this.keyString.indexOf(a.charAt(h++));f=this.keyString.indexOf(a.charAt(h++));g=this.keyString.indexOf(a.charAt(h++));c=c<<2|d>>4;d=(d&15)<<4|f>>2;e=(f&3)<<6|g;b+=String.fromCharCode(c);if(f!=64)b+=String.fromCharCode(d);if(g!=64)b+=String.fromCharCode(e)}return M.Cypher.utf8_decode(b)}});m_require("core/foundation/object.js");
M.SHA256=M.Object.extend({type:"M.SHA256",chrsz:8,hexcase:0,hash:function(a){a=M.Cypher.utf8_encode(a);return this.binb2hex(this.core_sha256(this.str2binb(a),a.length*this.chrsz))},safe_add:function(a,b){var c=(a&65535)+(b&65535);return(a>>16)+(b>>16)+(c>>16)<<16|c&65535},S:function(a,b){return a>>>b|a<<32-b},R:function(a,b){return a>>>b},Ch:function(a,b,c){return a&b^~a&c},Maj:function(a,b,c){return a&b^a&c^b&c},Sigma0256:function(a){return this.S(a,2)^this.S(a,13)^this.S(a,22)},Sigma1256:function(a){return this.S(a,
6)^this.S(a,11)^this.S(a,25)},Gamma0256:function(a){return this.S(a,7)^this.S(a,18)^this.R(a,3)},Gamma1256:function(a){return this.S(a,17)^this.S(a,19)^this.R(a,10)},core_sha256:function(a,b){var c=[1116352408,1899447441,3049323471,3921009573,961987163,1508970993,2453635748,2870763221,3624381080,310598401,607225278,1426881987,1925078388,2162078206,2614888103,3248222580,3835390401,4022224774,264347078,604807628,770255983,1249150122,1555081692,1996064986,2554220882,2821834349,2952996808,3210313671,
3336571891,3584528711,113926993,338241895,666307205,773529912,1294757372,1396182291,1695183700,1986661051,2177026350,2456956037,2730485921,2820302411,3259730800,3345764771,3516065817,3600352804,4094571909,275423344,430227734,506948616,659060556,883997877,958139571,1322822218,1537002063,1747873779,1955562222,2024104815,2227730452,2361852424,2428436474,2756734187,3204031479,3329325298],d=[1779033703,3144134277,1013904242,2773480762,1359893119,2600822924,528734635,1541459225],e=Array(64),f,g,h,i,j,k,
n,p,o,m,l,q;a[b>>5]|=128<<24-b%32;a[(b+64>>9<<4)+15]=b;for(o=0;o<a.length;o+=16){f=d[0];g=d[1];h=d[2];i=d[3];j=d[4];k=d[5];n=d[6];p=d[7];for(m=0;m<64;m++){e[m]=m<16?a[m+o]:this.safe_add(this.safe_add(this.safe_add(this.Gamma1256(e[m-2]),e[m-7]),this.Gamma0256(e[m-15])),e[m-16]);l=this.safe_add(this.safe_add(this.safe_add(this.safe_add(p,this.Sigma1256(j)),this.Ch(j,k,n)),c[m]),e[m]);q=this.safe_add(this.Sigma0256(f),this.Maj(f,g,h));p=n;n=k;k=j;j=this.safe_add(i,l);i=h;h=g;g=f;f=this.safe_add(l,q)}d[0]=
this.safe_add(f,d[0]);d[1]=this.safe_add(g,d[1]);d[2]=this.safe_add(h,d[2]);d[3]=this.safe_add(i,d[3]);d[4]=this.safe_add(j,d[4]);d[5]=this.safe_add(k,d[5]);d[6]=this.safe_add(n,d[6]);d[7]=this.safe_add(p,d[7])}return d},str2binb:function(a){for(var b=[],c=(1<<this.chrsz)-1,d=0;d<a.length*this.chrsz;d+=this.chrsz)b[d>>5]|=(a.charCodeAt(d/this.chrsz)&c)<<24-d%32;return b},binb2hex:function(a){for(var b=this.hexcase?"0123456789ABCDEF":"0123456789abcdef",c="",d=0;d<a.length*4;d++)c+=b.charAt(a[d>>2]>>
(3-d%4)*8+4&15)+b.charAt(a[d>>2]>>(3-d%4)*8&15);return c}});m_require("core/foundation/request.js");M.INFO=0;M.DEBUG=1;M.WARN=2;M.ERR=3;
M.Logger=M.Object.extend({type:"M.Logger",_remoteAccess:YES,log:function(a,b){b=b||M.DEBUG;if(M.Application.getConfig("debugMode")!==false){if(typeof console==="undefined"){window.console={};console.log=console.info=console.warn=console.error=function(){}}switch(b){case M.DEBUG:this.debug(a);break;case M.ERR:this.error(a);break;case M.WARN:this.warn(a);break;case M.INFO:this.info(a);break;default:this.debug(a)}}},debug:function(a){console.debug(a)},error:function(a){console.error(a)},warn:function(a){console.warn(a)},
info:function(a){console.info(a)},remote:function(a){var b=this;try{if(b._remoteAccess){var c=JSON.stringify(a);$.ajax({url:"/__espresso_debug_console__",data:c,type:"POST"}).done(function(){b._remoteAccess=YES}).fail(function(){b._remoteAccess=NO})}}catch(d){M.Logger.error(d)}}});m_require("core/utility/logger.js");m_require("core/utility/environment.js");
M.EventDispatcher=M.Object.extend({type:"M.EventDispatcher",lastEvent:{},registerEvents:function(a,b,c,d){if(!b||typeof b!=="object")M.Logger.log("No events passed for '"+a+"'!",M.WARN);else{a=this.getEventSource(a);this.checkEventSource(a)&&_.each(b,function(e,f){M.EventDispatcher.registerEvent(f,a,e,c,d,YES)})}},registerEvent:function(a,b,c,d,e,f){if(!f){if(!c||typeof c!=="object"){M.Logger.log("No event passed!",M.WARN);return}b=this.getEventSource(b);if(!this.checkEventSource(b))return}d&&_.indexOf(d,
a)>-1||(e&&typeof e==="string"?M.Logger.log("Event type '"+a+"' not recommended for "+e+"!",M.WARN):M.Logger.log("Event type '"+a+"' not recommended!",M.WARN));if(this.checkHandler(c,a)){a==="enter"&&b.bind("keyup",function(h){h.which===13&&$(this).trigger("enter")});var g=this;M.ViewManager.getViewById(b.attr("id"));b.bind(a,function(h){if(b.attr("id")&&M.ViewManager.getViewById(b.attr("id")).type==="M.DashboardItemView")if(g.lastEvent.tap&&g.lastEvent.tap.view==="M.DashboardItemView"&&g.lastEvent.tap.x===
h.clientX&&g.lastEvent.tap.y===h.clientY)return;else if(g.lastEvent.taphold&&g.lastEvent.taphold.view==="M.DashboardItemView"&&g.lastEvent.taphold.x===h.clientX&&g.lastEvent.taphold.y===h.clientY)return;var i=YES;if(b.attr("id")){var j=M.ViewManager.getViewById(b.attr("id"));if(j.type==="M.SearchBarView")i=NO;else if((a==="click"||a==="tap")&&j.type==="M.ButtonView"&&j.parentView&&j.parentView.type==="M.ToggleView"&&j.parentView.toggleOnClick)i=NO;else if(j.hyperlinkTarget&&j.hyperlinkType)i=NO;else if(a===
"pageshow")i=NO}if(i){h.preventDefault();h.stopPropagation()}if(M.ViewManager.getViewById(b.attr("id")))g.lastEvent[a]={view:M.ViewManager.getViewById(b.attr("id")).type,date:+new Date,x:h.clientX,y:h.clientY};c.nextEvent?g.bindToCaller(c.target,c.action,[h.currentTarget.id?h.currentTarget.id:h.currentTarget,h,c.nextEvent])():g.bindToCaller(c.target,c.action,[h.currentTarget.id?h.currentTarget.id:h.currentTarget,h])()})}},unregisterEvents:function(a){a=this.getEventSource(a);this.checkEventSource(a)&&
a.unbind()},unregisterEvent:function(a,b){b=this.getEventSource(b);this.checkEventSource(b)&&b.unbind(a)},callHandler:function(a,b,c,d){if(this.checkHandler(a,b&&b.type?b.type:"undefined"))c?this.bindToCaller(a.target,a.action,[b.currentTarget.id?b.currentTarget.id:b.currentTarget,b])():this.bindToCaller(a.target,a.action,d)()},checkHandler:function(a,b){if(typeof a.action==="string")if(a.target)if(a.target[a.action]&&typeof a.target[a.action]==="function"){a.action=a.target[a.action];return YES}else{M.Logger.log("No action '"+
a.action+"' found for given target and the event type '"+b+"'!",M.WARN);return NO}else{M.Logger.log("No valid target passed for action '"+a.action+"' and the event type '"+b+"'!",M.WARN);return NO}else if(typeof a.action!=="function"){M.Logger.log("No valid action passed for the event type '"+b+"'!",M.WARN);return NO}return YES},getEventSource:function(a){return a=typeof a==="string"?$("#"+a+":first"):$(a)},checkEventSource:function(a){if(!a){M.Logger.log("The event source is invalid!",M.WARN);return NO}return YES},
dispatchOrientationChangeEvent:function(){var a=M.Environment.getOrientation();if(a===M.PORTRAIT_BOTTOM||a===M.PORTRAIT_TOP){$("html").removeClass("landscape");$("html").addClass("portrait")}else{$("html").removeClass("portrait");$("html").addClass("landscape")}$("#"+M.ViewManager.getCurrentPage().id).trigger("orientationdidchange")}});m_require("core/utility/location.js");M.LOCATION_PERMISSION_DENIED="PERMISSION_DENIED";M.LOCATION_POSITION_UNAVAILABLE="POSITION_UNAVAILABLE";M.LOCATION_TIMEOUT="TIMEOUT";
M.LOCATION_UNKNOWN_ERROR="UNKNOWN_ERROR";M.LOCATION_NOT_SUPPORTED="NOT_SUPPORTED";M.LOCATION_ALREADY_RECEIVING="ALREADY_RECEIVING";M.LOCATION_TYPE_APPROXIMATE=0;M.LOCATION_TYPE_GEOMETRIC_CENTER=1;M.LOCATION_TYPE_RANGE_INTERPOLATED=2;M.LOCATION_TYPE_ROOFTOP=3;M.LOCATION_GEOCODER_ERROR="ERROR";M.LOCATION_GEOCODER_INVALID_REQUEST="INVALID_REQUEST";M.LOCATION_GEOCODER_OVER_QUERY_LIMIT="OVER_QUERY_LIMIT";M.LOCATION_GEOCODER_REQUEST_DENIED="REQUEST_DENIED";M.LOCATION_GEOCODER_UNKNOWN_ERROR="UNKNOWN_ERROR";
M.LOCATION_GEOCODER_ZERO_RESULTS="ZERO_RESULTS";
M.LocationManager=M.Object.extend({type:"M.LocationManager",lastLocationUpdate:null,geoCoder:null,isGettingLocation:NO,getLocation:function(a,b,c,d){if(this.isGettingLocation){M.Logger.log("M.LocationManager is currently already trying to retrieve a location.",M.WARN);this.bindToCaller(a,c,M.LOCATION_ALREADY_RECEIVING)()}else this.isGettingLocation=YES;var e=this;this.lastLocationUpdate=M.Date.now();d=d?d:{};d.enableHighAccuracy=d.enableHighAccuracy?d.enableHighAccuracy:NO;d.maximumAge=d.maximumAge?
d.maximumAge:0;d.timeout=d.timeout?d.timeout:3E3;navigator&&navigator.geolocation?navigator.geolocation.getCurrentPosition(function(f){e.isGettingLocation=NO;if(!d.accuracy||d.accuracy&&f.coords.accuracy<=d.accuracy){f=M.Location.extend({latitude:f.coords.latitude,longitude:f.coords.longitude,accuracy:f.coords.accuracy,date:M.Date.now()});e.bindToCaller(a,b,f)()}else{M.Logger.log("Location retrieved, but accuracy too low: "+f.coords.accuracy,M.INFO);f=M.Date.now();d.timeout-=e.lastLocationUpdate.timeBetween(f);
e.getLocation(a,b,c,d)}},function(f){e.isGettingLocation=NO;switch(f.code){case 1:e.bindToCaller(a,c,M.LOCATION_PERMISSION_DENIED)();break;case 2:e.bindToCaller(a,c,M.LOCATION_POSITION_UNAVAILABLE)();break;case 3:e.bindToCaller(a,c,M.LOCATION_TIMEOUT)();break;default:e.bindToCaller(a,c,M.LOCATION_UNKNOWN_ERROR)()}},d):e.bindToCaller(e,c,M.LOCATION_NOT_SUPPORTED)()},getLocationByAddress:function(a,b,c,d){if(d&&typeof d==="string"){if(!this.geoCoder)this.geoCoder=new google.maps.Geocoder;var e=this;
this.geoCoder.geocode({address:d,language:M.I18N.getLanguage().substr(0,2),region:M.I18N.getLanguage().substr(3,2)},function(f,g){if(g==google.maps.GeocoderStatus.OK){var h=null;_.each(f,function(i){if(!h||M["LOCATION_TYPE_"+h.geometry.location_type]<M["LOCATION_TYPE_"+i.geometry.location_type])h=i});h&&e.bindToCaller(a,b,M.Location.init(h.geometry.location.lat(),h.geometry.location.lng()))()}else switch(g){case "ERROR":e.bindToCaller(a,c,M.LOCATION_GEOCODER_ERROR)();break;case "INVALID_REQUEST":e.bindToCaller(a,
c,M.LOCATION_GEOCODER_INVALID_REQUEST)();break;case "OVER_QUERY_LIMIT":e.bindToCaller(a,c,M.LOCATION_GEOCODER_OVER_QUERY_LIMIT)();break;case "REQUEST_DENIED":e.bindToCaller(a,c,M.LOCATION_GEOCODER_REQUEST_DENIED)();break;case "ZERO_RESULTS":e.bindToCaller(a,c,M.LOCATION_GEOCODER_ZERO_RESULTS)();break;default:e.bindToCaller(a,c,M.LOCATION_GEOCODER_UNKNOWN_ERROR)()}})}},getAddressByLocation:function(a,b,c,d,e){if(d&&typeof d==="object"&&d.type==="M.Location"){if(!this.geoCoder)this.geoCoder=new google.maps.Geocoder;
var f=this;this.geoCoder.geocode({location:new google.maps.LatLng(d.latitude,d.longitude),language:M.I18N.getLanguage().substr(0,2),region:M.I18N.getLanguage().substr(3,2)},function(g,h){if(h==google.maps.GeocoderStatus.OK)if(g[0]&&e){var i={};_.each(g[0].address_components,function(j){_.each(j.types,function(k){i[k]=j.long_name?j.long_name:j.short_name})});f.bindToCaller(a,b,i)()}else g[0]?f.bindToCaller(a,b,g[0].formatted_address)():f.bindToCaller(a,c,M.LOCATION_GEOCODER_ZERO_RESULTS)();else switch(h){case "ERROR":f.bindToCaller(a,
c,M.LOCATION_GEOCODER_ERROR)();break;case "INVALID_REQUEST":f.bindToCaller(a,c,M.LOCATION_GEOCODER_INVALID_REQUEST)();break;case "OVER_QUERY_LIMIT":f.bindToCaller(a,c,M.LOCATION_GEOCODER_OVER_QUERY_LIMIT)();break;case "REQUEST_DENIED":f.bindToCaller(a,c,M.LOCATION_GEOCODER_REQUEST_DENIED)();break;case "ZERO_RESULTS":f.bindToCaller(a,c,M.LOCATION_GEOCODER_ZERO_RESULTS)();break;default:f.bindToCaller(a,c,M.LOCATION_GEOCODER_UNKNOWN_ERROR)()}})}}});m_require("core/utility/cypher_algorithms/base64.js");
m_require("core/utility/cypher_algorithms/sha256.js");
M.Cypher=M.Object.extend({type:"M.Cypher",defaultDecoder:M.Base64,defaultEncoder:M.Base64,defaultHasher:M.SHA256,decode:function(a,b){return b&&b.decode?b.decode(a):this.defaultDecoder.decode(a)},encode:function(a,b){return b&&b.encode?b.encode(a):this.defaultEncoder.encode(a)},hash:function(a,b){return b&&b.hash?b.hash(a):this.defaultHasher.hash(a)},utf8_encode:function(a){a=a.replace(/\r\n/g,"\n");for(var b="",c=0;c<a.length;c++){var d=a.charCodeAt(c);if(d<128)b+=String.fromCharCode(d);else{if(d>
127&&d<2048)b+=String.fromCharCode(d>>6|192);else{b+=String.fromCharCode(d>>12|224);b+=String.fromCharCode(d>>6&63|128)}b+=String.fromCharCode(d&63|128)}}return b},utf8_decode:function(a){for(var b="",c=0,d=c1=c2=0;c<a.length;){d=a.charCodeAt(c);if(d<128){b+=String.fromCharCode(d);c++}else if(d>191&&d<224){c2=a.charCodeAt(c+1);b+=String.fromCharCode((d&31)<<6|c2&63);c+=2}else{c2=a.charCodeAt(c+1);c3=a.charCodeAt(c+2);b+=String.fromCharCode((d&15)<<12|(c2&63)<<6|c3&63);c+=3}}return b}});m_require("core/utility/logger.js");
M.DataConsumer=M.Object.extend({type:"M.DataConsumer",responsePath:null,httpMethod:"GET",appendRecords:YES,urlParams:null,configure:function(a){return this.extend(a)},find:function(a){this.include(a);var b=this;M.Request.init({url:this.bindToCaller(this,this.url,_.toArray(this.urlParams))(),isJSON:YES,callbacks:{success:{target:this,action:function(c){if(c){if(this.responsePath){var d=this.responsePath.split(".");_.each(d,function(f){c=c[f]})}if(c&&!_.isArray(c)||_.isArray(c)&&c.length>0){_.isArray(c)||
(c=[c]);var e=[];_.each(c,function(f){f=a.model.createRecord(b.map(f));e.push(f)});this.callbacks&&M.EventDispatcher.checkHandler(this.callbacks.success)&&M.EventDispatcher.callHandler(this.callbacks.success,null,NO,[e])}else{M.Logger.log("There were no data sets found in response path '"+this.responsePath+"'.",M.INFO);this.callbacks&&M.EventDispatcher.checkHandler(this.callbacks.success)&&M.EventDispatcher.callHandler(this.callbacks.success,null,NO,[[]])}}else{M.Logger.log("There was no data returned for url '"+
this.bindToCaller(this,this.url,_.toArray(this.urlParams))()+"'.",M.INFO);this.callbacks&&M.EventDispatcher.checkHandler(this.callbacks.success)&&M.EventDispatcher.callHandler(this.callbacks.success,null,NO,[[]])}}},error:{target:this,action:function(c,d){this.callbacks&&M.EventDispatcher.checkHandler(this.callbacks.error)&&M.EventDispatcher.callHandler(this.callbacks.error,null,NO,d)}}}}).send()},map:function(){},url:function(){}});m_require("core/utility/logger.js");
M.DataProvider=M.Object.extend({type:"M.DataProvider",isAsync:NO,find:function(){},save:function(){},del:function(){},check:function(a,b){return a[b]?YES:NO}});M.TARGET_REMOTE="remote";M.TARGET_LOCAL="local";M.TARGET_BOTH="both";M.PRIO_REMOTE="prio_remote";M.PRIO_LOCAL="prio_local";M.PRIO_BOTH="prio_both";m_require("core/utility/logger.js");
M.DataProviderHybrid=M.Object.extend({type:"M.DataProviderHybrid",isAsync:YES,localProvider:null,remoteProvider:null,usedProviders:0,callbackCounter:0,onSuccess:null,onError:null,callbacks:{success:{local:null,remote:null},error:{local:null,remote:null}},config:null,configure:function(a){a=this.extend({config:a});if(!a.config.local)throw M.Error.extend({code:M.ERR_MODEL_PROVIDER_NOT_SET,msg:"No local data provider passed"});if(!a.config.remote)throw M.Error.extend({code:M.ERR_MODEL_PROVIDER_NOT_SET,
msg:"No remote data provider passed"});a.localProvider=a.config.local;a.remoteProvider=a.config.remote;return a},find:function(a){this.crud(a,"find")},save:function(a){this.crud(a,"save")},del:function(a){this.crud(a,"del")},crud:function(a,b){a.target=a.target||M.TARGET_BOTH;if(!a.prio)if(a.target===M.TARGET_BOTH)a.prio=M.PRIO_BOTH;else if(a.target===M.TARGET_LOCAL)a.prio=M.PRIO_LOCAL;else if(a.target===M.PRIO_REMOTE)a.prio=M.PRIO_REMOTE;this.callbackCounter=0;this.setOriginCallbacks(a);this.setIntermediateCallbacks(a);
switch(a.target){case M.TARGET_LOCAL:this.usedProviders=1;this.localProvider[b](a);break;case M.TARGET_REMOTE:this.usedProviders=1;this.remoteProvider[b](a);break;case M.TARGET_BOTH:this.usedProviders=2;this.localProvider[b](a);this.remoteProvider[b](a)}},setOriginCallbacks:function(a){if(a.onSuccess&&a.onSuccess.target&&a.onSuccess.action){a.onSuccess=this.bindToCaller(a.onSuccess.target,a.onSuccess.target[a.onSuccess.action]);this.onSuccess=a.onSuccess}else if(a.onSuccess==="function")this.onSuccess=
a.onSuccess;if(a.onError&&a.onError.target&&a.onError.action){a.onError=this.bindToCaller(a.onError.target,a.onError.target[a.onSuccess.action]);this.onError=a.onError}else if(a.onError==="function")this.onError=a.onError},setIntermediateCallbacks:function(a){a.onSuccess={target:this,action:"handleSuccessCallback"};a.onError={target:this,action:"handleErrorCallback"}},handleSuccessCallback:function(a,b,c){if(c.type===this.localProvider.type)this.callbacks.success.local={result:a,param:b,dataProvider:c};
else if(c.type===this.remoteProvider.type)this.callbacks.success.remote={result:a,param:b,dataProvider:c};this.callbackCounter+=1;this.callbackCounter===this.usedProviders&&this.calculateOperationState()},handleErrorCallback:function(a,b,c){if(c.type===this.localProvider.type)this.callbacks.error.local={err:a,param:b,dataProvider:c};else if(c.type===this.remoteProvider.type){this.callbacks.error.remote={err:a,param:b,dataProvider:c};b.model.state_remote=M.STATE_FAIL}this.callbackCounter+=1;this.callbackCounter===
this.usedProviders&&this.calculateOperationState()},calculateOperationState:function(a){switch(a.prio){case M.PRIO_LOCAL:this.callbacks.success.local?this.onSuccess(this.success.local.result,a):this.onError(this.error.local.err,a);case M.PRIO_REMOTE:this.callbacks.error.local?this.onSuccess(this.success.remote.result,a):this.onError(this.error.remote.err,a);case M.PRIO_BOTH:!this.callbacks.success.local||!this.callbacks.success.remote?this.onError(this.error.remote.err,a):this.onSuccess(this.success.remote.result,
a)}}});m_require("core/utility/logger.js");M.ModelAttribute=M.Object.extend({type:"M.ModelAttribute",dataType:null,isRequired:NO,isUpdated:NO,validators:null,refEntity:null,validate:function(a){var b=YES,c;for(c in this.validators)this.validators[c].validate(a)||(b=NO);return b}});
M.ModelAttribute.attr=function(a,b){b||(b={});if(!b.dataType)b.dataType=a||"String";if(!b.validators&&b.isRequired)b.validators=[];b.isRequired&&_.select(b.validators,function(c){return c.type==="M.PresenceValidator"}).length===0&&b.validators.push(M.PresenceValidator);return this.extend(b)};m_require("core/utility/logger.js");M.Validator=M.Object.extend({type:"M.Validator",validationErrors:[],customize:function(a){return this.extend(a)},clearErrorBuffer:function(){this.validationErrors.length=0}});
m_require("core/utility/logger.js");M.ERR_UNDEFINED=0;M.ERR_CONNECTION=1;M.ERR_VALIDATION_PRESENCE=100;M.ERR_VALIDATION_URL=101;M.ERR_VALIDATION_PHONE=102;M.ERR_VALIDATION_NUMBER=103;M.ERR_VALIDATION_NOTMINUS=104;M.ERR_VALIDATION_EMAIL=105;M.ERR_VALIDATION_DATE=106;M.ERR_MODEL_PROVIDER_NOT_SET=120;M.ERR_WEBSQL_UNKNOWN=200;M.ERR_WEBSQL_DATABASE=201;M.ERR_WEBSQL_VERSION=202;M.ERR_WEBSQL_TOO_LARGE=203;M.ERR_WEBSQL_QUOTA=204;M.ERR_WEBSQL_SYNTAX=205;M.ERR_WEBSQL_CONSTRAINT=206;M.ERR_WEBSQL_TIMEOUT=207;
M.ERR_WEBSQL_PROVIDER_NO_DBHANDLER=208;M.ERR_WEBSQL_BULK_NO_RECORDS=210;M.ERR_COUCHDB_CONFLICT=300;M.ERR_COUCHDB_DBNOTFOUND=301;M.ERR_COUCHDB_DBEXISTS=302;M.ERR_COUCHDB_DOCNOTFOUND=303;M.Error=M.Object.extend({code:"",msg:"",errObj:null});M.STATE_UNDEFINED="state_undefined";M.STATE_NEW="state_new";M.STATE_INSYNCPOS="state_insyncpos";M.STATE_INSYNCNEG="state_insyncneg";M.STATE_LOCALCHANGED="state_localchange";M.STATE_VALID="state_valid";M.STATE_INVALID="state_invalid";M.STATE_DELETED="state_deleted";
m_require("core/utility/logger.js");
M.Model=M.Object.extend({type:"M.Model",name:"",m_id:null,record:null,__meta:{},recordManager:null,modelList:{},state:M.STATE_UNDEFINED,state_remote:M.STATE_UNDEFINED,usesValidation:NO,dataProvider:null,getUniqueId:function(){return M.UniqueId.uuid(4)},createRecord:function(a){var b=this.extend({m_id:a.m_id?a.m_id:this.getUniqueId(),record:a});delete a.m_id;b.state=a.state?a.state:M.STATE_NEW;delete a.state;if(b.state===M.STATE_NEW){b.record[M.META_CREATED_AT]=+new Date;b.record[M.META_UPDATED_AT]=
+new Date}for(var c in b.record)if(!(c===M.META_CREATED_AT||c===M.META_UPDATED_AT))if(b.__meta.hasOwnProperty(c)){b.__meta[c].dataType==="Reference"&&b.record[c]&&b.record[c].type&&b.record[c].type==="M.Model"&&b.set(c,b.record[c]);if(b.__meta[c])b.__meta[c].isUpdated=NO}else{M.Logger.log('Deleting "'+c+"\" property. It's not part of "+this.name+" definition.",M.WARN);delete b.record[c]}this.recordManager.add(b);return b},create:function(a,b){var c=M.Model.extend({__meta:{},name:a.__name__,dataProvider:b,
recordManager:{},usesValidation:a.usesValidation?a.usesValidation:this.usesValidation});delete a.__name__;delete a.usesValidation;for(var d in a)if(typeof a[d]==="function")c[d]=a[d];else if(a[d].type==="M.ModelAttribute")c.__meta[d]=a[d];c.__meta[M.META_CREATED_AT]=this.attr("String",{isRequired:YES});c.__meta[M.META_UPDATED_AT]=this.attr("String",{isRequired:YES});c.recordManager=M.RecordManager.extend({records:[]});return this.modelList[c.name]=c},hasOne:function(a,b){return this.attr("Reference",
{refType:"toOne",reference:a,validators:b.validators,isRequired:b.isRequired})},hasMany:function(a,b){return this.attr("Reference",{refType:"toMany",reference:b})},attr:function(a,b){return M.ModelAttribute.attr(a,b)},get:function(a,b){var c=this.__meta[a],d=this.record[a];if(c&&c.dataType==="Reference")if(c.refEntity)return c.refEntity;else if(d)if(b&&b.force){this.deepFind([{prop:a,name:c.reference,model:this.modelList[c.reference],m_id:d}],this.dataProvider.isAsync?b.onSuccess:null);if(!this.dataProvider.isAsync)return c.refEntity;
return YES}else return(c=this.recordManager.getRecordById(d))?c:NO;else return null;return d},set:function(a,b){if(this.__meta[a].dataType==="Reference"&&b.type&&b.type==="M.Model"){if(this.record[a]!==b.m_id){this.record[a]=b.m_id;this.__meta[a].refEntity=b}}else if(this.record[a]!==b){this.record[a]=b;this.__meta[a].isUpdated=YES;this.record[M.META_UPDATED_AT]=+new Date}},records:function(){if(this.recordManager&&this.recordManager.records)return this.recordManager.records},validate:function(){var a=
YES;M.Validator.clearErrorBuffer();var b=this.state===M.STATE_NEW?this.__meta:this.record,c;for(c in b)if(c!=="ID")this.__meta[c].validate({value:this.record[c],modelId:this.name+"_"+this.m_id,property:c})||(a=NO);return a},find:function(a){this.dataProvider||M.Logger.log("No data provider given.",M.ERR);a=a?a:{};a.deleteRecordList=a.deleteRecordList?a.deleteRecordList:YES;a.deleteRecordList&&this.recordManager.removeAll();this.dataProvider||M.Logger.log("No data provider given.",M.ERR);return this.dataProvider.find($.extend(a,
{model:this}))},save:function(a){this.dataProvider||M.Logger.log("No data provider given.",M.ERR);a=a?a:{};if(!this.m_id)return NO;var b=YES;if(this.usesValidation)b=this.validate();if(a.cascade)for(var c in this.__meta)this.__meta[c]&&this.__meta[c].dataType==="Reference"&&this.__meta[c].refEntity&&this.__meta[c].refEntity.save({cascade:YES});if(b)return this.dataProvider.save($.extend(a,{model:this}))},del:function(a){this.dataProvider||M.Logger.log("No data provider given.",M.ERR);a=a?a:{};if(!this.m_id)return NO;
if(this.dataProvider.del($.extend(a,{model:this}))){this.state=M.STATE_DELETED;return YES}},complete:function(a){var b=[],c;for(c in this.record)this.__meta[c].dataType==="Reference"&&b.push({prop:c,name:this.__meta[c].reference,model:this.modelList[this.__meta[c].reference],m_id:this.record[c]});this.deepFind(b,a)},deepFind:function(a,b){if(a.length<1)b&&b();else{var c=a.pop();this.bindToCaller(this,this.deepFind,[a,b]);switch(this.dataProvider.type){case "M.DataProviderLocalStorage":var d=this.modelList[c.name].find({key:c.m_id});
this.__meta[c.prop].refEntity=d;this.deepFind(a,b)}}},setReference:function(a,b,c,d){b.__meta[c].refEntity=a[0];d()}});m_require("core/utility/logger.js");
M.Observable=M.Object.extend({type:"M.Observable",bindingList:null,attach:function(a,b){if(!this.bindingList)this.bindingList=[];this.bindingList.push({observer:a,observable:b})},detach:function(a){this.bindingList=_.filter(this.bindingList,function(b){return b.observable!==a})},notifyObservers:function(a){_.each(this.bindingList,function(b){if(a===b.observable||b.observable.indexOf(".")>0&&b.observable.indexOf(a)>-1||a.indexOf(".")>0&&b.observable.indexOf(a.substring(0,a.lastIndexOf("."))))b.observer.valueBinding&&
(a===b.observer.valueBinding.property||a===b.observer.valueBinding.property.split(".")[0])?b.observer.valueDidChange():b.observer.contentDidChange()})}});m_require("core/datastore/data_provider.js");M.DataProviderDummy=M.DataProvider.extend({find:function(){M.Logger.log("DummyProvider does not support find().",M.WARN)},save:function(){M.Logger.log("DummyProvider does not support save().",M.WARN)},del:function(){M.Logger.log("DummyProvider does not support del().",M.WARN)}});m_require("core/datastore/data_provider.js");
M.DataProviderLocalStorage=M.DataProvider.extend({type:"M.DataProviderLocalStorage",save:function(a){try{var b=JSON.stringify(a.model.record);localStorage.setItem(M.LOCAL_STORAGE_PREFIX+M.Application.name+M.LOCAL_STORAGE_SUFFIX+a.model.name+"_"+a.model.m_id,b);return YES}catch(c){M.Logger.log("Error saving "+a.model.record+" to localStorage with key: "+M.LOCAL_STORAGE_PREFIX+M.Application.name+M.LOCAL_STORAGE_SUFFIX+a.model.name+"_"+this.m_id,M.WARN);M.Logger.log("Error "+c.code+", "+c.name+": "+
c.message);return NO}},del:function(a){try{if(localStorage.getItem(M.LOCAL_STORAGE_PREFIX+M.Application.name+M.LOCAL_STORAGE_SUFFIX+a.model.name+"_"+a.model.m_id)){localStorage.removeItem(M.LOCAL_STORAGE_PREFIX+M.Application.name+M.LOCAL_STORAGE_SUFFIX+a.model.name+"_"+a.model.m_id);a.model.recordManager.remove(a.model.m_id);return YES}return NO}catch(b){M.Logger.log("Error removing key: "+M.LOCAL_STORAGE_PREFIX+M.Application.name+M.LOCAL_STORAGE_SUFFIX+a.model.name+"_"+a.model.m_id+" from localStorage",
M.WARN);return NO}},find:function(a){if(a.key){var b=this.findByKey(a);if(!b)return NO;var c=RegExp("^"+M.LOCAL_STORAGE_PREFIX+M.Application.name+M.LOCAL_STORAGE_SUFFIX+a.model.name+"_([0-9a-zA-Z]+)$").exec(a.key);c=c&&c[1]?c[1]:null;if(!c){M.Logger.log("retrieved model has no valid key: "+a.key,M.ERR);return NO}return a.model.createRecord($.extend(b,{m_id:c,state:M.STATE_VALID}))}if(a.query){var d=a.query;c=[];d.identifier||c.push("identifier");d.operator||c.push("operator");if(d.value===undefined||
d.value===null)c.push("value");if(c.length>0){M.Logger.log("Wrong query format:",c.join(", ")," is/are missing.",M.WARN);return[]}var e=d.identifier;c=d.operator;var f=d.value;if((d=this.findAll(a))&&d.length>0){var g=d[0];if(typeof g.record[e]!=g.__meta[e].dataType.toLowerCase())if(!(g.__meta[e].dataType.toLowerCase()=="reference"&&typeof g.record[e]=="string"))throw'Query: "'+e+c+f+'" tries to compare '+typeof g.record[e]+" with "+g.__meta[e].dataType.toLowerCase()+".";}switch(c){case "=":d=_.select(d,
function(i){return i.record[e]===f});break;case "~=":if(a.model.__meta[e].dataType.toLowerCase()!=="string")throw'Query: Operator "~=" only works on string properties. Property "'+e+'" is of type '+a.model.__meta[e].dataType.toLowerCase()+".";a=["\\\\","\\*","\\+","\\?","\\|","\\{","\\}","\\[","\\]","\\(","\\)","\\^","\\$","\\.","\\#"];for(b in a)f=f.replace(RegExp(a[b],"g"),"\\"+a[b].substring(1,2));f=f.replace(/\s/g,"\\s");var h=RegExp(f);d=_.select(d,function(i){return h.test(i.record[e])});break;
case "!=":d=_.select(d,function(i){return i.record[e]!==f});break;case "<":d=_.select(d,function(i){return i.record[e]<f});break;case ">":d=_.select(d,function(i){return i.record[e]>f});break;case "<=":d=_.select(d,function(i){return i.record[e]<=f});break;case ">=":d=_.select(d,function(i){return i.record[e]>=f});break;default:M.Logger.log("Query has unknown operator: "+c,M.WARN);d=[]}return d}else return this.findAll(a)},findByKey:function(a){if(a.key){a.key=RegExp("^"+M.LOCAL_STORAGE_PREFIX+M.Application.name+
M.LOCAL_STORAGE_SUFFIX).test(a.key)?a.key:M.LOCAL_STORAGE_PREFIX+M.Application.name+M.LOCAL_STORAGE_SUFFIX+a.model.name+"_"+a.key;return localStorage.getItem(a.key)?this.buildRecord(a.key,a):NO}M.Logger.log("Please provide a key.",M.WARN);return NO},findAll:function(a){for(var b=[],c=0;c<localStorage.length;c++){var d=localStorage.key(c);if(regexResult=RegExp("^"+M.LOCAL_STORAGE_PREFIX+M.Application.name+M.LOCAL_STORAGE_SUFFIX+a.model.name+"_").exec(d)){var e=this.buildRecord(d,a);if(d=(d=RegExp("^"+
M.LOCAL_STORAGE_PREFIX+M.Application.name+M.LOCAL_STORAGE_SUFFIX+a.model.name+"_([0-9a-zA-Z]+)$").exec(d))&&d[1]?d[1]:null){e=a.model.createRecord($.extend(e,{m_id:d,state:M.STATE_VALID}));b.push(e)}else M.Logger.log("Model Record m_id not correct: "+d,M.ERR)}}return b},buildRecord:function(a,b){var c=JSON.parse(localStorage.getItem(a)),d;for(d in c)if(b.model.__meta[d]&&typeof c[d]!==b.model.__meta[d].dataType.toLowerCase())switch(b.model.__meta[d].dataType){case "Date":c[d]=M.Date.create(c[d])}return c},
allKeys:function(a){for(var b=[],c=0;c<localStorage.length;c++){var d=localStorage.key(c);(regexResult=RegExp("^"+M.LOCAL_STORAGE_PREFIX+M.Application.name+M.LOCAL_STORAGE_SUFFIX+a.model.name+"_").exec(d))&&b.push(d)}return b}});m_require("core/datastore/data_provider.js");
M.DataProviderRemoteStorage=M.DataProvider.extend({type:"M.DataProviderRemoteStorage",config:null,save:function(a){var b=this.config[a.model.name],c=null;if(a.model.state===M.STATE_NEW){c=b.create.map(a.model.record);this.remoteQuery("create",b.url+b.create.url(a.model.get("ID")),b.create.httpMethod,c,a,null)}else{c=b.update.map(a.model.record);this.remoteQuery("update",b.url+b.update.url(a.model.get("ID")),b.update.httpMethod,c,a,function(d){d.setRequestHeader("X-Http-Method-Override",b.update.httpMethod)})}},
del:function(a){var b=this.config[a.model.name],c=b.del.url(a.model.get("ID"));c=b.url+c;this.remoteQuery("delete",c,b.del.httpMethod,null,a,function(d){d.setRequestHeader("X-Http-Method-Override",b.del.httpMethod)})},find:function(a){var b=this.config[a.model.name],c=a.ID?b.read.url.one(a.ID):b.read.url.all();c=b.url+c;this.remoteQuery("read",c,b.read.httpMethod,null,a)},createModelsFromResult:function(a,b,c){var d=[],e=this.config[c.model.name];if(_.isArray(a))for(var f in a)d.push(c.model.createRecord($.extend(e.read.map(a[f]),
{state:M.STATE_VALID})));else typeof a==="object"&&d.push(c.model.createRecord($.extend(e.read.map(a),{state:M.STATE_VALID})));b(d)},remoteQuery:function(a,b,c,d,e,f){var g=this,h=this.config[e.model.name];M.Request.init({url:b,method:c,isJSON:YES,contentType:"application/JSON",data:d?d:null,onSuccess:function(i){a==="delete"&&e.model.recordManager.remove(e.model.m_id);if(a==="create")h.create.receiveIdentifier?h.create.receiveIdentifier(i,e.model):M.Logger.log("No ID receiving operation defined.");
if(e.onSuccess)if(e.onSuccess.target&&e.onSuccess.action){e.onSuccess=g.bindToCaller(e.onSuccess.target,e.onSuccess.target[e.onSuccess.action],[i]);a==="read"?g.createModelsFromResult(i,e.onSuccess,e):e.onSuccess()}else typeof e.onSuccess==="function"&&g.createModelsFromResult(i,e.onSuccess,e);else M.Logger.log("No success callback given.",M.WARN)},onError:function(i,j){var k=M.Error.extend({code:M.ERR_CONNECTION,msg:j});e.onError&&typeof e.onError==="function"&&e.onError(k);if(e.onError&&e.onError.target&&
e.onError.action){e.onError=this.bindToCaller(e.onError.target,e.onError.target[e.onError.action],k);e.onError()}else typeof e.onError!=="function"&&M.Logger.log("No error callback given.",M.WARN)},beforeSend:f?f:null}).send()},configure:function(a){console.log("configure() called.");return this.extend({config:a})}});m_require("core/datastore/validator.js");
M.DateValidator=M.Validator.extend({type:"M.DateValidator",patternDateUS:/^([0-9]{2})\/([0-9]{2})\/([0-9]{4})(\s+([0-9]{2})\:([0-9]{2})(\:([0-9]{2}))?)?$/,patternDateDE:/^([0-9]{2})\.([0-9]{2})\.([0-9]{4})(\s+([0-9]{2})\:([0-9]{2})(\:([0-9]{2}))?)?$/,validate:function(a,b){if(a.isView){if(a.value===null||a.value===undefined||a.value===""||!(this.patternDateUS.test(a.value)||this.patternDateDE.test(a.value))||!M.Date.create(a.value)){var c=M.Error.extend({msg:this.msg?this.msg:b+" is not a valid date.",
code:M.ERR_VALIDATION_DATE,errObj:{msg:this.msg?this.msg:b+" is not a valid date.",viewId:a.id,validator:"DATE",onSuccess:a.onSuccess,onError:a.onError}});this.validationErrors.push(c);return NO}}else if(a.value.type&&a.value.type!=="M.Date"&&(a.value===null||a.value===undefined||a.value===""||!M.Date.create(a.value))){c=M.Error.extend({msg:this.msg?this.msg:a.property+" is not a valid date.",code:M.ERR_VALIDATION_DATE,errObj:{msg:this.msg?this.msg:a.property+" is not a valid date.",modelId:a.modelId,
validator:"DATE",onSuccess:a.onSuccess,onError:a.onError}});this.validationErrors.push(c);return NO}return YES}});m_require("core/datastore/validator.js");
M.EmailValidator=M.Validator.extend({type:"M.EmailValidator",pattern:/^((?:(?:(?:\w[\.\-\+]?)*)\w)+)\@((?:(?:(?:\w[\.\-\+]?){0,62})\w)+)\.(\w{2,6})$/,validate:function(a){if(typeof a.value!=="string")return NO;if(this.pattern.test(a.value))return YES;this.validationErrors.push(M.Error.extend({msg:this.msg?this.msg:a.value+" is not a valid email adress.",code:M.ERR_VALIDATION_EMAIL,errObj:{msg:a.value+" is not a valid email adress.",modelId:a.modelId,property:a.property,viewId:a.viewId,validator:"EMAIL",
onSuccess:a.onSuccess,onError:a.onError}}));return NO}});m_require("core/datastore/validator.js");
M.NotMinusValidator=M.Validator.extend({type:"M.NotMinusValidator",validate:function(a){if(typeof a.value==="number"){if(a.value<0){a=M.Error.extend({msg:this.msg?this.msg:a.value+" is a minus value. This is not allowed.",code:M.ERR_VALIDATION_NOTMINUS,errObj:{msg:a.value+" is a minus value. This is not allowed.",modelId:a.modelId,property:a.property,viewId:a.viewId,validator:"NUMBER",onSuccess:a.onSuccess,onError:a.onError}});this.validationErrors.push(a);return NO}return YES}if(typeof a.value===
"string"){if(this.pattern.exec(a.value)){a=M.Error.extend({msg:this.msg?this.msg:a.value+" is a minus value. This is not allowed.",code:M.ERR_VALIDATION_NOTMINUS,errObj:{msg:a.value+" is a minus value. This is not allowed.",modelId:a.modelId,property:a.property,viewId:a.viewId,validator:"NUMBER",onSuccess:a.onSuccess,onError:a.onError}});this.validationErrors.push(a);return NO}return YES}}});m_require("core/datastore/validator.js");
M.NumberValidator=M.Validator.extend({type:"M.NumberValidator",validate:function(a){if(typeof a.value==="number")return YES;if(typeof a.value==="string"&&(parseIntRadixTen(a.value)==a.value||parseFloat(a.value)==a.value))return YES;this.validationErrors.push(M.Error.extend({msg:this.msg?this.msg:a.value+" is not a number.",code:M.ERR_VALIDATION_NUMBER,errObj:{msg:a.value+" is not a number.",modelId:a.modelId,property:a.property,viewId:a.viewId,validator:"NUMBER",onSuccess:a.onSuccess,onError:a.onError}}));
return NO}});m_require("core/datastore/validator.js");
M.PhoneValidator=M.Validator.extend({type:"M.PhoneValidator",pattern:/^[0-9-\/()+\.\s]+$/,validate:function(a){if(typeof(a.value!=="string"))return NO;if(this.pattern.exec(a.value))return YES;this.validationErrors.push(M.Error.extend({msg:this.msg?this.msg:a.value+" is not a phone number.",code:M.ERR_VALIDATION_PHONE,errObj:{msg:a.value+" is not a phone number.",modelId:a.modelId,property:a.property,viewId:a.viewId,validator:"PHONE",onSuccess:a.onSuccess,onError:a.onError}}));return NO}});m_require("core/datastore/validator.js");
M.PresenceValidator=M.Validator.extend({type:"M.PresenceValidator",validate:function(a,b){if(a.value===null||a.value===undefined||a.value===""){this.validationErrors.push(a.isView?M.Error.extend({msg:this.msg?this.msg:b+" is required and is not set.",code:M.ERR_VALIDATION_PRESENCE,errObj:{msg:this.msg?this.msg:b+" is required and is not set.",viewId:a.id,validator:"PRESENCE",onSuccess:a.onSuccess,onError:a.onError}}):M.Error.extend({msg:this.msg?this.msg:a.property+"is required and is not set.",code:M.ERR_VALIDATION_PRESENCE,
errObj:{msg:this.msg?this.msg:a.property+" is required and is not set.",modelId:a.modelId,property:a.property,validator:"PRESENCE",onSuccess:a.onSuccess,onError:a.onError}}));return NO}return YES}});m_require("core/datastore/validator.js");
M.UrlValidator=M.Validator.extend({type:"M.UrlValidator",pattern:/^(http[s]\:\/\/)?[a-zA-Z0-9\-\.]+\.[a-zA-Z]{2,3}(\/\S*)?$/,validate:function(a){if(typeof(a.value!=="string"))return NO;if(this.pattern.exec(a.value))return YES;this.validationErrors.push(M.Error.extend({msg:this.msg?this.msg:a.value+" is not a valid url.",code:M.ERR_VALIDATION_URL,errObj:{msg:a.value+" is not a valid url.",modelId:a.modelId,property:a.property,viewId:a.viewId,validator:"PHONE",onSuccess:a.onSuccess,onError:a.onError}}));
return NO}});m_require("core/foundation/model.js");
M.RecordManager=M.Object.extend({type:"M.RecordManager",records:[],add:function(a){this.records.push(a)},addMany:function(a){if(_.isArray(a))this.records=this.records.concat(a);else a.type==="M.Model"&&this.add(a)},removeAll:function(){this.records.length=0},remove:function(a){if(a){var b=this.getRecordById(a);if(b)this.records=_.select(this.records,function(c){return c.m_id!==b.m_id});delete b}else M.Logger.log("No id given.",M.WARN)},getRecordForId:function(a){return this.getRecordById(a)},getRecordById:function(a){return _.detect(this.records,
function(b){return b.m_id===a})},dumpRecords:function(){_.each(this.records,function(a){console.log(a)})}});m_require("core/foundation/model.js");
M.View=M.Object.extend({type:"M.View",isView:YES,value:null,computedValue:null,contentBinding:null,contentBindingReverse:null,valueBinding:null,childViews:null,hasFocus:NO,id:null,isInline:NO,isEnabled:YES,parentView:null,modelId:null,cssClass:null,cssStyle:null,cssClassOnError:null,cssClassOnInit:null,html:"",triggerActionOnChange:NO,triggerActionOnKeyUp:NO,triggerActionOnEnter:NO,events:null,internalEvents:null,recommendedEvents:null,parentPage:null,design:function(a){a=this.extend(a);a.id=M.ViewManager.getNextId();
M.ViewManager.register(a);a.attachToObservable();return a},render:function(){this.renderChildViews();return this.html},renderUpdate:function(){},renderChildViews:function(){if(this.childViews){var a=this.getChildViewsAsArray(),b;for(b in a){if(this[a[b]]){this[a[b]]._name=a[b];this[a[b]].parentView=this;this.html+=this[a[b]].render()}else{this.childViews=this.childViews.replace(a[b]," ");M.Logger.log("There is no child view '"+a[b]+"' available for "+this.type+" ("+(this._name?this._name+", ":"")+
"#"+this.id+")! It will be excluded from the child views and won't be rendered.",M.WARN)}if(this.type==="M.PageView"&&this[a[b]].type==="M.TabBarView"){this.hasTabBarView=YES;this.tabBarView=this[a[b]]}}return this.html}},removeChildViews:function(){var a=this.getChildViewsAsArray(),b;for(b in a){this[a[b]].childViews&&this[a[b]].removeChildViews();this[a[b]].destroy();M.ViewManager.unregister(this[a[b]])}$("#"+this.id).empty()},getChildViewsAsArray:function(){try{return this.childViews?$.trim(this.childViews.replace(/\s+/g,
" ")).split(" "):[]}catch(a){return[]}},getValues:function(){var a={};if(this.childViews){var b=this.getChildViewsAsArray(),c;for(c in b){if(Object.getPrototypeOf(this[b[c]]).hasOwnProperty("getValue"))a[b[c]]=this[b[c]].getValue();if(this[b[c]].childViews){var d=this[b[c]].getValues(),e;for(e in d)a[e]=d[e]}}}return a},getValue:function(){},getIds:function(){var a={};if(this.childViews){var b=this.getChildViewsAsArray(),c;for(c in b){if(this[b[c]].id)a[b[c]]=this[b[c]].id;if(this[b[c]].childViews){var d=
this[b[c]].getIds(),e;for(e in d)a[e]=d[e]}}}return a},clearHtml:function(){this.html="";if(this.childViews){var a=this.getChildViewsAsArray(),b;for(b in a)this[a[b]].clearHtml()}},computeValue:function(){if(this.computedValue)this.value=this.computedValue.operation(this.computedValue.valuePattern?this.value:this.computedValue.value,this)},theme:function(){this.themeChildViews()},registerEvents:function(){var a={},b;for(b in this.events){if(b==="orientationchange")b="orientationdidchange";a[b]=this.events[b]}if(this.internalEvents)for(b in this.internalEvents)if(this.internalEvents[b])if(b===
"orientationchange"){this.internalEvents.orientationdidchange=this.internalEvents[b];delete this.internalEvents[b]}if(this.internalEvents&&a){for(b in a)if(this.internalEvents[b]){this.internalEvents[b].nextEvent=a[b];delete a[b]}M.EventDispatcher.registerEvents(this.id,this.internalEvents,this.recommendedEvents,this.type)}else this.internalEvents&&M.EventDispatcher.registerEvents(this.id,this.internalEvents,this.recommendedEvents,this.type);a&&M.EventDispatcher.registerEvents(this.id,a,this.recommendedEvents,
this.type);if(this.childViews){a=this.getChildViewsAsArray();for(var c in a)this[a[c]].registerEvents()}},themeChildViews:function(){if(this.childViews){var a=this.getChildViewsAsArray(),b;for(b in a)this[a[b]].theme()}},contentDidChange:function(){var a=this.contentBinding?this.contentBinding:this.computedValue?this.computedValue.contentBinding:null;if(a){var b=a.target;a=a.property.split(".");_.each(a,function(c){if(b)b=b[c]});if(!(b===undefined||b===null)){if(this.contentBinding)this.value=b;else if(this.computedValue.contentBinding)this.computedValue.value=
b;this.renderUpdate();this.delegateValueUpdate()}}},attachToObservable:function(){this.registerContentBinding();this.registervalueBinding()},registervalueBinding:function(){var a=this.valueBinding?this.valueBinding:this.computedValue?this.computedValue.valueBinding:null;a&&this.attachBinding(a,"valueBinding")},registerContentBinding:function(){var a=this.contentBinding?this.contentBinding:this.computedValue?this.computedValue.contentBinding:null;a&&this.attachBinding(a,"contentBinding")},attachBinding:function(a,
b){if(a)if(typeof a==="object")if(a.target&&typeof a.target==="object")if(a.property&&typeof a.property==="string"){var c=a.property.split(".");if(a.target[c[0]]!==undefined){if(!a.target.observable)a.target.observable=M.Observable.extend({});a.target.observable.attach(this,a.property);this.isObserver=YES}else M.Logger.log("The specified target for "+b+" for '"+this.type+"' ("+(this._name?this._name+", ":"")+"#"+this.id+")' has no property '"+a.property+"!",M.WARN)}else M.Logger.log("The type of the value of 'action' in "+
b+" for '"+this.type+"' ("+(this._name?this._name+", ":"")+"#"+this.id+")' is '"+typeof a.property+" but it must be of type 'string'!",M.WARN);else M.Logger.log("No valid target specified in "+b+" '"+this.type+"' ("+(this._name?this._name+", ":"")+"#"+this.id+")!",M.WARN);else M.Logger.log("No valid "+b+" specified for '"+this.type+"' ("+(this._name?this._name+", ":"")+"#"+this.id+")!",M.WARN)},setValueFromDOM:function(){},delegateValueUpdate:function(){this.contentBindingReverse&&this.hasFocus&&
this.contentBindingReverse.target.set(this.contentBindingReverse.property,this.value)},style:function(){},gotFocus:function(){this.hasFocus=YES},lostFocus:function(){this.hasFocus=NO},secure:function(a){return a.replace(/</g,"&lt;").replace(/>/g,"&gt;")},nl2br:function(a){if(a){if(typeof a!=="string")a=String(a);return a.replace(/\n/g,"<br />")}return a},tab2space:function(a){if(a){if(typeof a!=="string")a=String(a);return a.replace(/\t/g,"&#160;&#160;&#160;&#160;")}return a},clearValue:function(){},
clearValues:function(){if(this.childViews){var a=this.getChildViewsAsArray(),b;for(b in a){this[a[b]].childViews&&this[a[b]].clearValues();typeof this[a[b]].clearValue==="function"&&this[a[b]].clearValue()}}this.clearValue()},addCssClass:function(a){$("#"+this.id).addClass(a)},removeCssClass:function(a){$("#"+this.id).removeClass(a)},setCssProperty:function(a,b){$("#"+this.id).css(a,b)},removeCssProperty:function(a){this.setCssProperty(a,"")},getParentPage:function(){if(!this.parentPage)if(this.type===
"M.PageView")return this;else if(this.parentView)this.parentPage=this.parentView.getParentPage();else{var a=$("#"+this.id).parent().closest("[id^=m_]").attr("id");if(a)this.parentPage=M.ViewManager.getViewById(a).getParentPage()}return this.parentPage},findChildViews:function(a,b){var c=this,d=this.getChildViewsAsArray(),e=[];_.each(d,function(f){f===a&&e.push(c[f])});b&&_.each(d,function(f){e.push.apply(e,c[f].findChildViews(a,b))});return e}});M.TRANSITION={};M.TRANSITION.NONE="none";
M.TRANSITION.SLIDE="slide";M.TRANSITION.SLIDEUP="slideup";M.TRANSITION.SLIDEDOWN="slidedown";M.TRANSITION.POP="pop";M.TRANSITION.FADE="fade";M.TRANSITION.FLIP="flip";m_require("core/foundation/observable.js");
M.Controller=M.Object.extend({type:"M.Controller",observable:null,switchToTab:function(a,b){b||(b=NO);if(a.parentView&&a.parentView.type==="M.TabBarView"){var c=a.parentView.activeTab,d=M.ViewManager.getPage(a.page);a.parentView.setActiveTab(a);if(a===c)M.ViewManager.getCurrentPage()!==d&&this.switchToPage(d,M.TRANSITION.FLIP,b,NO);else this.switchToPage(d,M.TRANSITION.FLIP,b,YES)}else M.Logger.log("Please provide a valid tab bar item to the switchToTab method.",M.WARN)},switchToPage:function(a,b,
c,d){M.Date.now();if(a=a&&typeof a==="object"?a:M.ViewManager.getPage(a)){b=b?b:M.TRANSITION.SLIDE;c=c!==undefined?c:NO;d=d!==undefined?d:YES;if(a.type==="M.PageView")$.mobile.changePage($("#"+a.id),{transition:M.Application.getConfig("useTransitions")?b:M.TRANSITION.NONE,reverse:M.Application.getConfig("useTransitions")?c:NO,changeHash:d,showLoadMsg:NO});M.ViewManager.setCurrentPage(a)}else M.Logger.log('Page "'+a+'" not found',M.ERR)},set:function(a,b){var c=a.split(".");if(c.length===1)this[a]=
b;else{for(var d=this[c[0]]=this[c[0]]?this[c[0]]:{},e=1;e<c.length-1;e++)d=d[c[e]]=d[c[e]]?d[c[e]]:{};d[c[c.length-1]]=b}this.observable&&this.observable.notifyObservers(a)}});m_require("core/foundation/view.js");
M.ViewManager=M.Object.extend({type:"M.ViewManager",nextId:0,idPrefix:"m_",viewList:{},pageList:{},currentPage:null,currentlyRenderedPage:null,foundView:null,getNextId:function(){this.nextId+=1;return this.idPrefix+this.nextId},register:function(a){this.viewList[a.id]=a;if(a.type==="M.PageView")this.pageList[a.id]=a},unregister:function(a){delete this.viewList[a.id]},getViewById:function(a){return this.viewList[a]},findViewById:function(a){return this.getViewById(a)},getIdByView:function(a){return a.id},
getView:function(a,b){if(typeof a!=="object")a=M.Application.pages[a]?M.Application.pages[a]:M.ViewManager.getViewById(a)?M.ViewManager.getViewById(a):null;var c=null;this.foundView=null;if(a)c=this.findView(a,b);c||M.Logger.log("view '"+b+"' not found.",M.WARN);return c},findView:function(a,b){if(a.childViews){var c=a.getChildViewsAsArray(),d;for(d in c)if(b===c[d]){this.foundView=a[b];break}else this.findView(a[c[d]],b)}return this.foundView},getPage:function(a){var b=M.Application.pages[a];b||
M.Logger.log("page '"+a+"' not found.",M.WARN);return b},getCurrentPage:function(){return this.currentPage},setCurrentPage:function(a){this.currentPage=a},dumpViewList:function(){_.each(this.viewList,function(a){console.log(a.id+": "+a.type)})}});m_require("core/foundation/view_manager.js");
M.Application=M.Object.extend({type:"M.Application",name:null,currentLanguage:null,defaultLanguage:null,isFirstLoad:YES,entryPage:null,config:{},design:function(a){var b={},c;for(c in a)if(a[c]&&a[c].type==="M.PageView")b[c]=a[c];this.include({pages:b});this.entryPage=a.entryPage&&typeof a.entryPage==="string"?a.entryPage:null;return this},main:function(){var a=M.ViewManager.getPage(M.Application.entryPage.replace(/\s+/g,""));delete M.ViewManager.viewList[a.id];delete M.ViewManager.pageList[a.id];
a.id="m_entryPage";a.render();M.ViewManager.setCurrentPage(a);_.each(M.ViewManager.pageList,function(b){b.render()});M.ViewManager.viewList.m_entryPage=a;M.ViewManager.pageList.m_entryPage=a},getConfig:function(a){if(this.config.hasOwnProperty(a))return this.config[a];return null}});
(function(a){a.fn.outerMarginHeight=function(){if(!this||this.length<1)return null;var b=a(this).closest(".ui-page"),c=NO,d=b.css("left");if(!b.is(":visible")){b.addClass("ui-page-active").css("left",-window.innerWidth*4);c=YES}var e=this.outerHeight();e+=parseIntRadixTen(this.css("margin-bottom"));e+=parseIntRadixTen(this.css("margin-top"));c&&b.removeClass("ui-page-active").css("left",d);return e};a.fn.outerMarginWidth=function(){if(!this||this.length<1)return null;var b=a(this).closest(".ui-page"),
c=NO,d=b.css("left");if(!b.is(":visible")){b.addClass("ui-page-active").css("left",-window.innerWidth*4);c=YES}var e=this.outerWidth();e+=parseIntRadixTen(this.css("margin-left"));e+=parseIntRadixTen(this.css("margin-right"));c&&b.removeClass("ui-page-active").css("left",d);return e}})(jQuery);
