// ==========================================================================
// The M-Project - Mobile HTML5 Application Framework
// Generated with: Espresso 
//
// Project: DIGI-WebApp
// I18N: en_us
// ==========================================================================

M.I18N.en_us = {
	  mainMenu: "Mainmenu"
	, menu: "Menu"
	, bookTime: "book times"
	, timeRegistration: "Timetracking"
	, book: "Book"
	, book2: "book..."
	, closingTime: "Closing time"
	, handApplications: "Handorder"
	, dataTransfer: "Data&shy;transfer"
	, info: "Info and Language"
	, settings: "Settings"
	, timeData: "Timedata"
	, back: "back"
	, save: "save"
	, Save: "Save"
	, order: "Order"
	, position: "Position"
	, activity: "Activity"
	, employees: "Employee"
	, configuredUser: "User"
	, orderInfo: "Orderinfo"
	, orderName: "Ordername"
	, orderNumber: "Order-No."
	, orderDescription: "Orderdescription"
	, positionInfo: "Positioninfo"
	, positionNumber: "Position-No."
	, positionDescription: "Positiondescription"
	, doBooking: "Booking takes place..."
	, bookingDone: "The booking has been saved"
	, handApplication: "Handorder"
	, hint: "Hint"
	, error: "Error"
	, doClosingTime: "Closing time takes place..."
	, confirmClosingTimeMessage: "Are you sure, you want to book closing time?"
	, openBookingsOverwriteBySettingsUpdate : "There are open or not sent bookings. Do you indeed want to change the settings? All current bookings will be lost!"
	, yes: "Yes"
	, no: "No"
	, assume: "accept"
	, apply: "accept"
	, noOpenBookings: "Closing time cannot be booked as there is no open booking!"
	, connectionError: "Connectionerror"
	, connectionErrorMsg: "There was an error while connecting to the service!"
	, closingTimeDone: "Booking saved"
	, closingTimeDoneMessage: "Closing time has been successfully booked."
	, doDataTransfer: "Transfering data..."
	, confirmDataTransferMessage: "Should the datatransfer get startet?"
	, noDataToTransfer: "Datatransfer impossible as there are no new bookings to transfer."
	, dataTransferDone: "Datatransfer done"
	, dataTransferDoneMessage: "The data has successfully been transfered."
	, company: "Company"
	, password: "Password"
	, connectionCode: "Connectioncode"
	, workerId: "User-Id"
	, autoSyncAfterBookTimeCheck: "Auto-Transfer of master data"
	, autoTransferAfterBookTimeCheck: "Auto-Transfer after new booking"
	, autoTransferAfterClosingDayCheck: "Auto-Transfer after closing time"
	, autoSaveGPSData: "Save GPS-Data in bookings"
	, listOfTimeData: "List of all bookings"
	, selectSomething: "Select something ..."
	, noData: "No Data ..."
	, hintSelectApplication: "Cannot show orderdetails as no order has been chosen."
	, hintSelectPosition: "Cannot show positiondetails as no position has been chosen."
	, confirmSaveOfSettings: "Do you want to save the settings overwriting the former values?"
	, settingsSaveDone: "The settings have been saved."
	, settingsSaveDoneReloadApp: "The settings have been saved. The application will reload now."
	, settingsUpdateCanceled: "The saving of the settings has been canceled."
	, settingsSaveError: "The settings could not be saved. Try again later." 
	, getPositionsLoader: "Receiving positions"
	, getFeaturesLoader: "Receiving configuration"
	, getOrdersLoader: "Receiving orders"
	, getActivitiesLoader: "Receiving activities"
	, authenticateLoader: "Authenticate"
	, selectEmployee: "Select employee"
	, getWorkPlansLoader: "Receiving workplans"
	, getHandOrdersLoader: "Receiving handorders"
	, getKolonne: "Receiving crew"
	, authenticated: "Authentification successful."
	, authenticationError: "Authentification error"
	, authenticationErrorMsg: "You could not get authenticated. Please check settings."
	, authenticationError2: "Authentification error"
	, authenticationErrorMsg2: "Wrong User-Id"
	, authenticationError3: "Authentification error"
	, authenticationErrorMsg3: "Company and/or password were invalid"
	, ordersReceived: "Orders received"
	, handOrdersReceived: "Handorders received"
	, positionsReceived: "Positions received"
	, activitiesReceived: "Activities received"
	, workPlansReceived: "Workplans received"
	, kolonneReceived: "Crew received"
	, noOrderSelected: "No order selected"
	, noOrderSelectedMsg: "Please choose an order"
	, noPosSelected: "No Position selected"
	, noPosSelectedMsg: "Please choose a position"
	, noActSelected: "No activity selected"
	, noActSelectedMsg: "Please choose an activity"
	, doubleBooking: "Hint"
	, doubleBookingMsg: "No new booking as the selected data is the same as the current booking."
	, sendConfigurationMsg: "Send configuration"
	, sendConfigurationFail: "Transmission error"
	, sendConfigurationFailMsg: "The settings could not be transmitted. Check your internet connection and try again later."
	, sendDataMsg: "Sending Data"
	, sendDataFail: "Transmission error"
	, sendDataFailMsg: "The bookings could not be transmitted. Check your internet connection and try again later."
	, noHandOrderNameEntered: "Name missing"
	, noHandOrderNameEnteredMsg: "Please choose a name for this handorder."
	, specialCharProblem: "special character error"
	, specialCharProblemMsg: "Unsupported special characters! Use only: a-Z, 0-9, ä-Ü as well as: .,!?;:/'()+-=_$§%@€"
	, handOrderTooLong: "Name too long"
	, handOrderTooLongMsg: "The name of the handorder can have at most 16 characters."
	, handOrderExists: "Exists already"
	, handOrderExistsMsg: "There already exists a handorder with that name."
	, handOrderSaveSuccess: "Handorder saved"
	, handOrderSaveSuccessMsg: "The handorder has been saved."
	, handOrderSaveError: "Handorder not saved"
	, handOrderSaveErrorMsg: "The handorder could not be saved."
	, employeeSelection: "Select employees"
	, employeeSelectionMsg: "You have to select at least one employee for the crew."
	, employeeSelectionSuccess: "Selection successful"
	, employeeSelectionSuccessMsg: "Selection has been saved."
	, noCredentials: "No credentials"
	, noCredentialsMsg: "Please enter your credentials."
	, currentBookingSendSuccess: "Transmission successful"
	, currentBookingSendSuccessMsg: "All bookings successfully transmitted."
	, bookingSaved: "Booking saved"
	, bookingSavedMsg: "The booking has been saved."
	, closingDaySuccess: "Closing time booked"
	, closingDaySuccessMsg: "This work day has successfully been closed and transmitted."
	, closingDaySuccessWithoutMsg: "This work day has successfully been closed."
	, inputError: "Input error"
	, inputErrorOnlyNumbers: "Enter only numbers in this field."
	, offlineWork: "Offline"
	, offlineWorkMsg: "No connection could be established. You now work offline with the locally available data."
	, offlineWorkNotPossible: "No connection"
	, offlineWorkNotPossibleMsg: "Impossible to work offline as not all of the necessary data is available."
	, noOrdersAvailable: "Error"
	, noOrdersAvailableMsg: "There are no orders available for this User-Id!"
	, secretQuestion: "Delete all data?"
	, secretQuestionMsg: "ATTENTION: 'Yes' will reset DIGI-WebApp entirely!"
	, quitQuestion: "Exit DIGI-WebApp?"
	, quitQuestionMsg: "Do you want to exit DIGI-WebApp?"
	, latitude: "Latitude"
	, longitude: "Longitude"
	, GPSError: "GPS-Error"
	, GPSnotactive: "GPS-Reciever not enabled"
	, getGPSPositionMsg: "Receiving geolocation"
	, wrongPasswordMsg: "The given password was invalid!"
	, wrongPasswordTitle: "Invalid password"
	, GPSunavailable: "The GPS-Reciever is not enabled! No geolocation will be recorded!"
	, GPStimeout: "The current geoposition could not be determined!"
	, GPSmissingPermission: "DIGI-WebApp is missing the permission to determine a geoposition!"
	, GPSunknownError: "Unkown GPS-Error: "
	, ERROR: "Error"
	, media: "Media"
	, remark: "Remark"
	, remarkIsMandatory: "Remark is mandatory"
	, remarkIsMandatoryMessage: "You have to enter a remark!"
	, EditTimeDataPageTitle: "Edit"
	, remarkTooLong: "Remark too long"
	, remarkTooLongMessage: "The remark may be at most 255 characters long!"
	, open: "open"
	, now: "now"
	, oclock: ""
	, closeBooking: "Close booking"
	, logout: "logging out"
	, exitWebApp: "Exit DIGI-WebApp"
	, takePicture: "New photo"
	, takePictureDemo: "New photo (DEMO)"
	, mediaList: "Medialist"
	, saveAsContact: "as contact"
	, saveAsContactSuccess: "Contact successfully saved"
	, saveAsContactError: "Saving failed"
	, noContactsAvailable: "Contacts not available"
	, contactExistsMultiple: "The contact for this order exists multiple times!"
	, saveAsContactChangeQuestionTitle: "Change contact?"
	, saveAsContactChangeQuestionMsg: "A matching contact was found. Do you want to change that contact?"
	, saveAsContactChangeErrorMsg: "Error while saving contact"
	, contactLastChange: "Contact last changed"
	, showAddressInMap: "Search address in map"
	, showCoordinatesInMap: "Show in map"
	, showInMapOSMAlert: "We will now forward you to the chosen mapservices:\n\nOpenStreetMap"
	, showInMapGoogleAlert: "We will now forward you to the chosen mapservices:\n\nGoogle-Maps"
	, showInMapBingAlert: "We will now forward you to the chosen mapservices:\n\nBing-Maps"
	, updateApplication: "Update DIGI-WebApp"
	, applicationUpdateAvailable: "Update available"
	, applicationUpdateAvailableMsg: "DIGI-WebApp has been updated. Do you now want to switch to the newer version now?\n\nYou can as well update later with the update-button in the main menu."
	, noApplicationUpdateAvailable: "No update available"
	, noApplicationUpdateAvailableMsg: "DIGI-WebApp is already up to date"
	, useTransitionsSetting: "Transitions"
	, waitingForDevice: "Please wait ..."
	, recordAudio: "Audiorecording&shy; (DEMO)"
	, signature: "Signature"
	, materialPickUp: "Material pick up&shy; (DEMO)"
	, dailyChecklist: "Daily checklist&shy; (DEMO)"
	, loadSignatures: "Loading signatures ..."
	, phone: "Phone"
	, fax: "Fax"
	, email: "eMail"
	, ansprechpartner: "Contact person"
	, kundenname: "Customer name"
	, GPSDataIsMandatory: "Use of GPS-Data is mandatory"
	, Anwesenheitsliste: "Attendance list"
	, AnwesenheitslisteKonnteNichtGeladenWerden: "The attendance list could not be loaded!"
	, AnwesenheitslisteLaden: "Receiving attendance list"
	, Zeitbuchungen: "Bookings"
	, Zeitbuchung: "Booking"
	, ZeitbuchungenKonntenNichtGeladenWerden: "The bookings could not be loaded!"
	, ZeitbuchungenLaden: "Receiving bookings"
	, since: "since"
	, bookingSince: "current booking since"
	, empfangeUrlLoader: "Receiving databaseserver"
	, empfangeUrlError: "Unknown databaseserver"
	, empfangeUrlErrorMessage: "The appropriate databaseserver could not be determined!"
	, wrongServer: "Wrong server"
	, wrongServerMessage: "You started DIGI-WebApp on the wrong server! You will now be forwarded. Please check settings afterwards!"
	, notDefined: "not defined"
	, unknown: "unknown"
	, uploadMediaFiles: "Transmit media"
	, editPicture: "Edit Photo"
	, deleteLabel: "Delete"
	, errorWhileDeletingMediaFile: "Error while deleting mediafile!"
	, loadMediaFile: "loading mediafile"
	, saveMediaFile: "saving mediafile"
	, deleteMediaFile: "deleting mediafile"
	, profilingTook: "This transmission took"
	, geozoneTrafficlight: "Geozone traffic light"
	, showBookingCoordinatesInMap: "Show booking in map"
	, showPositionCoordinatesInMap: "Show order in map"
	, booking: "Booking"
	, positionLaden: "Loading positioninfo"
	, positionKonnteNichtGeladenWerden: "Could not load data!"
	, dauer: "Duration"
	, forward: "forward"
	, backward: "backward"
	, lastWorkday: "last work day"		
	, buchungskoordinaten: "Booking coordinates"		
	, auftragskoordinaten: "Order coordinates"
	, Monday: "Monday"
	, Tuesday: "Tuesday"
	, Wednesday: "Wednesday"
	, Thursday: "Thursday"
	, Friday: "Friday"
	, Saturday: "Saturday"
	, Sunday: "Sunday"
	, bookingRunningSince: "This booking is running since"
	, daysToHoldBookingsOnDeviceNaN: "The saved daycount was no number! Therefore only bookings for one day will be held available."
	, daysToHoldBookingsOnDeviceLabel: "Days to hold bookings available"
	, archivedTimeDataOf: "archived bookings of"
	, archivedTimeData: "archived bookings"
	, errorWhileArchivingBookings: "Error while archiving bookings!"
	, errorWhileBackingUpBookings: "Error while backing up bookings!"
	, fehlzeit: "Absence"
	, newFeatureActive: "New configuration"
	, newFeatureActiveMsg: "A new configuration was received. DIGI-WebApp will restart now to apply the new configuration."
	, appZuruecksetzen: "reset"
	, applicationLanguage: "Application language"
	, language_de_de: "Deutsch"
	, language_en_us: "English"
	, language_fr_fr: "Français"
	, language_es_es: "Español"
	, language_nl_nl: "Nederlands"
	, refresh: "refresh"
	, cancel: "cancel"
		
	, hour: "Hour"
	, hours: "Hours"
	, minute: "Minute"
	, minutes: "Minutes"

	// Start::Bautagebuch
	, Bautagebuch: "Builder's Diary"
	, BautagebuchBautageberichte: "Construction Records"
	, BautagebuchBautagebericht: "Construction Record"
	, BautagebuchAdd: "new"
	, BautagebuchDelete: "delete"
	, BautagebuchBautageberichtAbschliessen: "finish this Construction Record"
	, BautagebuchSaveOrClose: "save or finish"
	, BautagebuchMaterial: "Material"
	, BautagebuchMaterialien: "Material"
	, BautagebuchZeiten: "Bookings"
	// "Zeitbuchungen" wird auch hier verwendet
	, BautagebuchNotizen: "Notes"
	, BautagebuchNotiz: "Note"
	, BautagebuchMedien: "Media"
	, BautagebuchMedium: "Media"
	, BautagebuchStartUhrzeit: "daily start time"
    // Ende::Bautagebuch

};