M.ContainerView=M.View.extend({type:"M.ContainerView",render:function(){this.html+='<div id="'+this.id+'"'+this.style()+">";this.renderChildViews();this.html+="</div>";return this.html},style:function(){var a="";if(this.cssClass)a+=' class="'+this.cssClass+'"';return a}});
M.SliderView=M.View.extend({type:"M.SliderView",value:0,initialValue:0,min:0,max:100,step:1,isSliderOnly:NO,highlightLeftPart:NO,recommendedEvents:["change"],label:null,hasAsteriskOnLabel:NO,cssClassForAsterisk:null,render:function(){if(this.label){this.html+='<label for="'+this.id+'">'+this.label;this.html+=this.hasAsteriskOnLabel?this.cssClassForAsterisk?'<span class="'+this.cssClassForAsterisk+'">*</span></label>':"<span>*</span></label>":"</label>"}this.html+='<div id="'+this.id+'_container" class="tmp-slider-container'+
(this.isSliderOnly?" tmp-slider-is-slider-only":"")+'">';this.html+='<input id="'+this.id+'" type="range" data-highlight="'+this.highlightLeftPart+'" min="'+this.min+'" max="'+this.max+'" step="'+this.step+'" value="'+this.value+'"'+this.style()+">";this.html+="</div>";this.initialValue=this.value;return this.html},registerEvents:function(){if(!this.internalEvents)this.internalEvents={change:{target:this,action:"setValueFromDOM"}};this.bindToCaller(this,M.View.registerEvents)()},renderUpdate:function(){if(isNaN(this.value))this.value=
this.initialValue;else if(this.value<this.min)this.value=this.min;else if(this.value>this.max)this.value=this.max;$("#"+this.id).val(this.value);$("#"+this.id).slider("refresh")},setValueFromDOM:function(a,b,c){this.value=$("#"+this.id).val();c&&M.EventDispatcher.callHandler(c,b,NO,[this.value,this.id])},style:function(){var a="";if(this.cssClass)a+=' class="'+this.cssClass+'"';return a},theme:function(){this.isSliderOnly&&$("#"+this.id).hide();this.isEnabled||this.disable()},resetSlider:function(){this.value=
this.initialValue;this.renderUpdate()},disable:function(){this.isEnabled=NO;$("#"+this.id).slider("disable")},enable:function(){this.isEnabled=YES;$("#"+this.id).slider("enable")}});
M.DialogView=M.View.extend({type:"M.DialogView",isActive:NO,queue:[],showNowOrNever:NO,alert:function(a){if(this.isActive)this.enqueue("alert",a);else{this.isActive=YES;M.AlertDialogView.design(a).show()}},confirm:function(a){if(this.isActive)this.enqueue("confirm",a);else{this.isActive=YES;M.ConfirmDialogView.design(a).show()}},actionSheet:function(a){if(this.isActive)this.enqueue("actionSheet",a);else{this.isActive=YES;M.ActionSheetDialogView.design(a).show()}},enqueue:function(a,b){b.showNowOrNever||
this.queue.unshift({action:a,obj:b})},dequeue:function(){if(!this.isActive&&this.queue.length>0){var a=this.queue.pop();this[a.action](a.obj)}}});m_require("ui/dialog.js");
M.ConfirmDialogView=M.DialogView.extend({type:"M.ConfirmDialogView",title:"Confirm",message:"",confirmButtonValue:"Ok",cancelButtonValue:"Cancel",callbacks:null,render:function(){this.html='<div class="tmp-dialog-background"></div>';this.html+='<div id="'+this.id+'" class="tmp-dialog">';this.html+='<div class="tmp-dialog-header">';this.html+=this.title?this.title:"";this.html+="</div>";this.html+='<div class="tmp-dialog-content">';this.html+=this.message;this.html+="</div>";this.html+='<div class="tmp-dialog-footer">';
var a=M.ButtonView.design({value:this.confirmButtonValue,cssClass:"b tmp-dialog-smallerbtn-confirm",events:{tap:{target:this,action:"confirmed"}}}),b=M.ButtonView.design({value:this.cancelButtonValue,cssClass:"d tmp-dialog-smallerbtn-confirm",events:{tap:{target:this,action:"canceled"}}});this.html+=M.GridView.design({childViews:"confirm cancel",layout:M.TWO_COLUMNS,confirm:a,cancel:b}).render();this.html+="</div>";this.html+="</div>";$("body").append(this.html);if(a.type){a.registerEvents();a.theme()}if(b.type){b.registerEvents();
b.theme()}},show:function(){this.render();var a=$("#"+this.id),b=$(".tmp-dialog-background");this.positionDialog(a);this.positionBackground(b);a.addClass("pop in")},hide:function(){var a=$("#"+this.id),b=$(".tmp-dialog-background");a.addClass("pop out");b.remove();this.destroy();var c=this;window.setTimeout(function(){M.DialogView.isActive=NO;c.dequeue()},100)},confirmed:function(){this.hide();this.callbacks&&M.EventDispatcher.checkHandler(this.callbacks.confirm)&&this.bindToCaller(this.callbacks.confirm.target,
this.callbacks.confirm.action)()},canceled:function(){this.hide();this.callbacks&&M.EventDispatcher.checkHandler(this.callbacks.cancel)&&this.bindToCaller(this.callbacks.cancel.target,this.callbacks.cancel.action)()},positionDialog:function(a){var b=M.Environment.getSize(),c=window.pageYOffset,d=window.pageXOffset,e=a.outerHeight(),f=a.outerWidth();d=d+b[0]/2;b=c+b[1]/2;a.css("position","absolute");a.css("top",b+"px");a.css("left",d+"px");a.css("z-index",1E4);a.css("margin-top","-"+e/2+"px");a.css("margin-left",
"-"+f/2+"px")},positionBackground:function(a){a.css("height",$(document).height()+"px");a.css("width",$(document).width()+"px")}});m_require("ui/dialog.js");
M.AlertDialogView=M.DialogView.extend({type:"M.AlertDialogView",title:"Alert",message:"",hasConfirmButton:YES,confirmButtonValue:"Ok",callbacks:null,render:function(){this.html='<div class="tmp-dialog-background"></div>';this.html+='<div id="'+this.id+'" class="tmp-dialog">';this.html+='<div class="tmp-dialog-header">';this.html+=this.title?this.title:"";this.html+="</div>";this.html+='<div class="tmp-dialog-content">';this.html+=this.message;this.html+="</div>";var a;if(this.hasConfirmButton){this.html+=
'<div class="tmp-dialog-footer">';a=M.ButtonView.design({value:this.confirmButtonValue,cssClass:"b tmp-dialog-smallerbtn",events:{tap:{target:this,action:"handleCallback"}}});this.html+=a.render();this.html+="</div>"}this.html+="</div>";$("body").append(this.html);if(a.type){a.registerEvents();a.theme()}},show:function(){this.render();var a=$("#"+this.id),b=$(".tmp-dialog-background");this.positionDialog(a);this.positionBackground(b);a.addClass("pop in")},hide:function(){var a=$("#"+this.id),b=$(".tmp-dialog-background");
a.addClass("pop out");b.remove();this.destroy();var c=this;window.setTimeout(function(){M.DialogView.isActive=NO;c.dequeue()},100)},handleCallback:function(){this.hide();this.callbacks&&M.EventDispatcher.checkHandler(this.callbacks.confirm)&&this.bindToCaller(this.callbacks.confirm.target,this.callbacks.confirm.action)()},positionDialog:function(a){var b=M.Environment.getSize(),c=window.pageYOffset,d=window.pageXOffset,e=a.outerHeight(),f=a.outerWidth();d=d+b[0]/2;b=c+b[1]/2;a.css("position","absolute");
a.css("top",b+"px");a.css("left",d+"px");a.css("z-index",1E4);a.css("margin-top","-"+e/2+"px");a.css("margin-left","-"+f/2+"px")},positionBackground:function(a){a.css("height",$(document).height()+"px");a.css("width",$(document).width()+"px")}});m_require("ui/dialog.js");
M.ActionSheetDialogView=M.DialogView.extend({type:"M.ActionSheetDialogView",title:"ActionSheet",destructiveButtonValue:null,cancelButtonValue:null,otherButtonValues:null,otherButtonTags:null,deletionDelay:1E3,callbacks:null,render:function(){this.html='<div class="tmp-dialog-background"></div>';this.html+='<div id="'+this.id+'" class="tmp-actionsheet">';this.html+='<div class="tmp-dialog-header">';this.html+=this.title?this.title:"";this.html+="</div>";this.html+='<div class="tmp-dialog-footer">';
var a=this,b=[];this.destructiveButtonValue&&b.push(M.ButtonView.design({value:this.destructiveButtonValue,tag:"destruction",cssClass:"a tmp-actionsheet-destructive-button",events:{tap:{target:a,action:"handleCallback"}}}));if(this.otherButtonValues){if(this.otherButtonTags&&!_.isArray(this.otherButtonTags)&&!_.isArray(this.otherButtonValues)){M.Logger.log("Error in Action Sheet: Values and (optional) tags must be passed as string in an array! Rendering will not proceed.",M.WARN);return""}if(this.otherButtonTags&&
this.otherButtonTags.length!==this.otherButtonValues.length){M.Logger.log("Mismatch in Action Sheet: Number of other button's tags doesn't match number of values. Will not use given values, but use generated numbers as values.",M.WARN);this.otherButtonTags=null}var c=0;_.each(this.otherButtonValues,function(e){b.push(M.ButtonView.design({value:e,tag:a.otherButtonTags?a.otherButtonTags[c++]:c++,events:{tap:{target:a,action:"handleCallback"}}}))})}this.cancelButtonValue&&b.push(M.ButtonView.design({value:this.cancelButtonValue,
tag:"cancel",cssClass:"a",events:{tap:{target:a,action:"handleCallback"}}}));for(var d in b)this.html+=b[d].render();this.html+="</div>";this.html+="</div>";$("body").append(this.html);for(d in b){b[d].registerEvents();b[d].theme()}},show:function(){this.render();var a=$("#"+this.id);a.removeClass("slideup out reverse");a.addClass("slideup in")},hide:function(){var a=$("#"+this.id);a.removeClass("slideup in");a.addClass("slideup out reverse");$(".tmp-dialog-background").remove();var b=this;window.setTimeout(b.bindToCaller(b,
b.destroy),this.deletionDelay);b=this;window.setTimeout(function(){M.DialogView.isActive=NO;b.dequeue()},this.deletionDelay+100)},handleCallback:function(a){this.hide();a=M.ViewManager.getViewById(a);var b=a.tag==="destruction"||a.tag==="cancel"?a.tag:"other";this.callbacks&&b&&M.EventDispatcher.checkHandler(this.callbacks[b])&&this.bindToCaller(this.callbacks[b].target,this.callbacks[b].action,a.tag)()}});
M.DashboardItemView=M.View.extend({type:"M.DashboardItemView",icon:null,label:null,recommendedEvents:["click","tap","taphold","touchstart","touchmove","touchend","mousedown","mousemove","mouseup"],render:function(){this.html="";if(!this.icon){M.Logger.log("Please provide an icon for a dashboard item view!",M.WARN);return this.html}this.html+='<div id="'+this.id+'" class="tmp-dashboard-item" '+this.style()+">";this.html+=M.ImageView.design({value:this.icon}).render();this.html+='<div class="tmp-dashboard-item-label">'+
(this.label?this.label:this.value)+"</div>";this.html+="</div>";return this.html},registerEvents:function(){this.internalEvents={taphold:{target:this.parentView,action:"editDashboard"},tap:{target:this.parentView,action:"dispatchTapEvent"}};this.bindToCaller(this,M.View.registerEvents)()},style:function(){var a="";if(this.cssStyle)a+='style="'+this.cssStyle+'"';return a}});M.HORIZONTAL="horizontal";M.VERTICAL="vertical";
M.ButtonGroupView=M.View.extend({type:"M.ButtonGroupView",direction:M.HORIZONTAL,isInset:YES,isCompact:YES,buttonsPerLine:null,numberOfLines:null,currentLine:null,lines:null,activeButton:null,isSelectable:YES,recommendedEvents:["change"],render:function(){if(this.childViews){var a=this.getChildViewsAsArray();if(this.buttonsPerLine&&this.buttonsPerLine<a.length){var b=0,c;for(c in a)if(this[a[c]]&&this[a[c]].type==="M.ButtonView")b+=1;if(this.buttonsPerLine<b)this.numberOfLines=M.Math.round(b/this.buttonsPerLine,
M.FLOOR)}}if(this.numberOfLines){this.direction=M.HORIZONTAL;this.html+='<div id="'+this.id+'"';this.html+=this.style();this.html+=">";this.lines=[];for(c=0;c<this.numberOfLines;c++){this.currentLine=c+1;this.lines.push(this.id+"_"+c);this.html+='<div data-role="controlgroup" href="#" id="'+this.id+"_"+c+'" data-type="'+this.direction+'"';if(!this.isInset||this.isCompact)if(c==0)this.html+=this.isInset?' style="margin-bottom:0px"':' style="margin:0px"';else if(c>0&&c<this.numberOfLines-1)this.html+=
this.isInset?' style="margin:0px 0px 0px 0px"':' style="margin:0px"';else if(c<this.numberOfLines)this.html+=this.isInset?' style="margin-top:0px"':' style="margin:0px"';this.html+=">";this.renderChildViews();this.html+="</div>"}}else{this.html+='<div data-role="controlgroup" href="#" id="'+this.id+'" data-type="'+this.direction+'"'+this.style()+">";this.renderChildViews()}this.html+="</div>";return this.html},renderChildViews:function(){if(this.childViews){var a=this.getChildViewsAsArray(),b=0,c;
for(c in a)if(this[a[c]]&&this[a[c]].type==="M.ButtonView"){b+=1;if(!this.numberOfLines||M.Math.round(b/this.buttonsPerLine,M.CEIL)===this.currentLine){var d=this[a[c]];d.html="";d.parentView=this;d.internalEvents={tap:{target:this,action:"buttonSelected"}};if(this.direction===M.HORIZONTAL)d.cssStyle="margin-right:-2px;width:"+100/(this.numberOfLines?this.buttonsPerLine:a.length)+"%";this[a[c]]._name=a[c];this.html+=this[a[c]].render()}}else M.Logger.log("childview of button group is no button.",
M.WARN)}},theme:function(){if(this.numberOfLines)for(var a in this.lines){a=parseInt(a);$("#"+this.lines[a]).controlgroup();var b=this.getChildViewsAsArray(),c=0;if(this.isCompact)for(var d in b){d=parseInt(d);if(this[b[d]]&&this[b[d]].type==="M.ButtonView"){c+=1;var e=M.Math.round(c/this.buttonsPerLine,M.CEIL)-1,f=this[b[d]];if(a===e)if(a===0&&this.numberOfLines>1)if(c===1){$("#"+f.id).removeClass("ui-corner-left");this.isInset&&$("#"+f.id).addClass("ui-corner-tl")}else{if(c===this.buttonsPerLine){$("#"+
f.id).removeClass("ui-corner-right");this.isInset&&$("#"+f.id).addClass("ui-corner-tr")}}else if(a===this.numberOfLines-1)if(c===e*this.buttonsPerLine+1){$("#"+f.id).removeClass("ui-corner-left");$("#"+f.id).addClass("ui-corner-bl")}else{if(c===(e+1)*this.buttonsPerLine){$("#"+f.id).removeClass("ui-corner-right");$("#"+f.id).addClass("ui-corner-br")}}else if(c===e*this.buttonsPerLine+1)$("#"+f.id).removeClass("ui-corner-left");else c===(e+1)*this.buttonsPerLine&&$("#"+f.id).removeClass("ui-corner-right")}}}else $("#"+
this.id).controlgroup();if(this.childViews){b=this.getChildViewsAsArray();for(d in b)if(this[b[d]]&&this[b[d]].type==="M.ButtonView"){f=this[b[d]];f.isActive&&this.setActiveButton(f.id)}}},getActiveButton:function(){return this.activeButton},setActiveButton:function(a){if(this.isSelectable){if(this.activeButton){this.activeButton.removeCssClass("ui-btn-active");this.activeButton.isActive=NO}var b=M.ViewManager.getViewById(a);if(!b)if(a&&typeof a==="object"&&a.type==="M.ButtonView")b=a;if(b){b.addCssClass("ui-btn-active");
b.isActive=YES;this.activeButton=b}}},setActiveButtonAtIndex:function(a){if(this.childViews)(a=this[this.getChildViewsAsArray()[a]])&&a.type==="M.ButtonView"&&this.setActiveButton(a)},buttonSelected:function(a,b,c){if(!(M.ViewManager.getViewById(a)&&M.ViewManager.getViewById(a).type==="M.ButtonView"&&!M.ViewManager.getViewById(a).isEnabled)){if(!(this.activeButton&&this.activeButton===M.ViewManager.getViewById(a))){if(this.isSelectable){if(this.activeButton){this.activeButton.removeCssClass("ui-btn-active");
this.activeButton.isActive=NO}var d=M.ViewManager.getViewById(a);if(!d)if(a&&typeof a==="object"&&a.type==="M.ButtonView")d=a;if(d){d.addCssClass("ui-btn-active");d.isActive=YES;this.activeButton=d}}$("#"+this.id).trigger("change")}c&&M.EventDispatcher.callHandler(c,b,YES)}},style:function(){var a="";if(this.numberOfLines&&!this.isInset)a+=' class="ui-listview';if(this.cssClass)a+=a!==""?" "+this.cssClass:' class="'+this.cssClass;a+='"';return a}});
M.ToggleView=M.View.extend({type:"M.ToggleView",isInFirstState:YES,toggleOnClick:NO,currentView:null,render:function(){this.html+='<div id="'+this.id+'">';this.renderChildViews();this.html+="</div>";return this.html},renderChildViews:function(){if(this.childViews){var a=this.getChildViewsAsArray();if(a.length!==2)M.Logger.log("M.ToggleView requires exactly 2 child views, but "+a.length+" are given ("+(this.name?this.name+", ":"")+this.id+")!",M.WARN);else{for(var b in a)if(this[a[b]]){if(this.toggleOnClick)this[a[b]].internalEvents=
{tap:{target:this,action:"toggleView"}};this[a[b]]._name=a[b];this[a[b]].parentView=this;this.html+='<div id="'+this.id+"_"+b+'">';this.html+=this[a[b]].render();this.html+="</div>"}this.currentView=this[a[0]]}}},toggleView:function(a,b,c){a=(this.isInFirstState=!this.isInFirstState)?0:1;$("#"+this.id+"_"+a).show();$("#"+this.id+"_"+(a>0?0:1)).hide();var d=this.getChildViewsAsArray();if(this[d[a]])this.currentView=this[d[a]];$.mobile.fixedToolbars.show();c&&M.EventDispatcher.callHandler(c,b,YES)},
setView:function(a){if(typeof a==="string"){var b=this.getChildViewsAsArray();a=_.indexOf(b,a)>=0?this[a]:M.ViewManager.getViewById(a)?M.ViewManager.getViewById(a):a}if(a&&typeof a==="object"&&a.parentView===this)this.currentView!==a&&this.toggleView();else M.Logger.log("No valid view passed for toggle view '"+this._name+"'.",M.WARN)},theme:function(){if(this.currentView){this.themeChildViews();$("#"+this.id+"_"+((this.isInFirstState?0:1)>0?0:1)).hide()}}});
M.SearchBarView=M.View.extend({type:"M.SearchBarView",isListViewSearchBar:NO,listView:null,initialText:"",recommendedEvents:["focus","blur","enter","keyup"],render:function(){this.html+='<form role="search"'+this.style()+">";this.html+='<input id="'+this.id+'" type="search" value="'+(this.value?this.value:this.initialText)+'" class="'+this.cssClass+'" />';this.html+="</form>";return this.html},registerEvents:function(){this.internalEvents={focus:{target:this,action:"gotFocus"},blur:{target:this,action:"lostFocus"},
keyup:{target:this,action:"setValueFromDOM"}};this.bindToCaller(this,M.View.registerEvents)()},renderUpdate:function(){$("#"+this.id).val(this.value);this.styleUpdate()},setValueFromDOM:function(a,b,c){this.value=this.secure($("#"+this.id).val());this.delegateValueUpdate();c&&M.EventDispatcher.callHandler(c,b,YES)},style:function(){var a="";if(this.isListViewSearchBar)a+=' class="ui-listview-filter"';return a},styleUpdate:function(){this.isInline?$("#"+this.id).attr("display","inline"):$("#"+this.id).removeAttr("display");
this.isEnabled?$("#"+this.id).removeAttr("disabled"):$("#"+this.id).attr("disabled","disabled")},gotFocus:function(){if(this.initialText&&(!this.value||this.initialText===this.value)){this.setValue("");this.cssClassOnInit&&this.removeCssClass(this.cssClassOnInit)}this.hasFocus=YES},lostFocus:function(){if(this.initialText&&!this.value){this.setValue(this.initialText,NO);this.value="";this.cssClassOnInit&&this.addCssClass(this.cssClassOnInit)}this.hasFocus=NO},setValue:function(a,b){this.value=a;this.renderUpdate();
b&&this.delegateValueUpdate()},disable:function(){this.isEnabled=NO;this.renderUpdate()},enable:function(){this.isEnabled=YES;this.renderUpdate()},clearValue:function(){this.setValue("");this.lostFocus()},theme:function(){this.initialText&&!this.value&&this.cssClassOnInit&&this.addCssClass(this.cssClassOnInit);var a=this;$("#"+this.id).siblings("a.ui-input-clear").bind("tap",function(){a.setValue("",YES)})},getValue:function(){return this.value}});m_require("ui/search_bar.js");
M.ListView=M.View.extend({type:"M.ListView",removeItemsOnUpdate:YES,isDividedList:NO,cssClassForDivider:null,isCountedList:NO,cssClassForCounter:null,cssClassForSplitView:null,items:null,inEditMode:NO,editOptions:null,isNumberedList:NO,listItemTemplateView:null,isInset:NO,doNotOverlapAtTop:NO,doNotOverlapAtBottom:NO,searchBar:M.SearchBarView,hasSearchBar:NO,usesDefaultSearchBehaviour:YES,searchBarInitialText:"Search...",onSearchStringDidChange:null,idName:null,selectedItem:null,render:function(){if(!M.ViewManager.currentlyRenderedPage.listList)M.ViewManager.currentlyRenderedPage.listList=
[];M.ViewManager.currentlyRenderedPage.listList.push(this);if(this.hasSearchBar&&!this.usesDefaultSearchBehaviour){this.searchBar.isListViewSearchBar=YES;this.searchBar.listView=this;this.searchBar=M.SearchBarView.design(this.searchBar);this.html+=this.searchBar.render()}var a=this.isNumberedList?"ol":"ul";this.html+="<"+a+' id="'+this.id+'" data-role="listview"'+this.style()+"></"+a+">";return this.html},registerEvents:function(){this.bindToCaller(this,M.View.registerEvents)();this.hasSearchBar&&
!this.usesDefaultSearchBehaviour&&this.searchBar.registerEvents()},addItem:function(a){$("#"+this.id).append(a)},removeAllItems:function(){$("#"+this.id).empty()},renderUpdate:function(){this.removeItemsOnUpdate&&this.removeAllItems();var a=this;if(this.contentBinding&&typeof this.contentBinding.target==="object"&&typeof this.contentBinding.property==="string"&&this.contentBinding.target[this.contentBinding.property]){var b=this.contentBinding.target[this.contentBinding.property],c=this.listItemTemplateView;
if(c){if(this.items)b=b[this.items];this.isDividedList?_.each(b,function(d,e){a.renderListItemDivider(e);a.renderListItemView(d,c)}):this.renderListItemView(b,c);this.themeUpdate();$.mobile.fixedToolbars.show()}else M.Logger.log("The template view could not be loaded! Maybe you forgot to use m_require to set up the correct load order?",M.ERR)}else M.Logger.log("The specified content binding for the list view ("+this.id+") is invalid!",M.WARN)},renderListItemDivider:function(a){var b=M.ListItemView.design({});
b.value=a;b.isDivider=YES;this.addItem(b.render());b.theme()},renderListItemView:function(a,b){var c=this;_.each(a,function(d){var e=b.design({});if(d.type==="M.Model")e.modelId=d.m_id;else if(d.id||!isNaN(d.id))e.modelId=d.id;else if(d[c.idName]||d[c.idName]==="")e.modelId=d[c.idName];var f=e.getChildViewsAsArray();d=d.type==="M.Model"?d.record:d;for(var g in f){e[f[g]]=e[f[g]].design({});var h=null;if(h=e[f[g]].computedValue?/^<%=\s+([.|_|-|$|\u00a7|a-zA-Z]+[0-9]*[.|_|-|$|\u00a7|a-zA-Z]*)\s*%>$/.exec(e[f[g]].computedValue.valuePattern):
/^<%=\s+([.|_|-|$|\u00a7|a-zA-Z]+[0-9]*[.|_|-|$|\u00a7|a-zA-Z]*)\s*%>$/.exec(e[f[g]].valuePattern))switch(e[f[g]].type){case "M.LabelView":case "M.ButtonView":case "M.ImageView":case "M.TextFieldView":e[f[g]].value=d[h[1]]}}if(c.inEditMode){e.inEditMode=c.inEditMode;e.deleteButton=e.deleteButton.design({modelId:e.modelId,events:{tap:{target:c.editOptions.target,action:c.editOptions.action}},internalEvents:{tap:{target:c,action:"removeListItem"}}})}e.parentView=c;c.addItem(e.render());e.registerEvents();
e.deleteButton&&e.deleteButton.registerEvents();for(g in f)e[f[g]].theme()})},theme:function(){if(this.searchBar){if($("#"+this.id)&&$("#"+this.id).parent()){var a=0;$("#"+this.id).parent().find("form.ui-listview-filter").each(function(){a+=1;a!=1&&$(this).remove()})}this.searchBar.theme()}},themeUpdate:function(){$("#"+this.id).listview("refresh")},toggleRemove:function(a){if(this.contentBinding&&typeof this.contentBinding.target==="object"&&typeof this.contentBinding.property==="string"&&this.contentBinding.target[this.contentBinding.property]){this.inEditMode=
!this.inEditMode;this.editOptions=a;this.renderUpdate()}},setActiveListItem:function(a,b,c){this.selectedItem&&this.selectedItem.removeCssClass("ui-btn-active");this.selectedItem=M.ViewManager.getViewById(a);this.listItemTemplateView&&this.listItemTemplateView.isSelectable&&this.selectedItem.addCssClass("ui-btn-active");c&&M.EventDispatcher.callHandler(c,b,NO,[a,this.selectedItem.modelId])},resetActiveListItem:function(){this.selectedItem&&this.selectedItem.removeCssClass("ui-btn-active")},style:function(){var a=
"";if(this.cssClass||this.doNotOverlapAtTop||this.doNotOverlapAtBottom)a+=' class="'+(this.cssClass?this.cssClass:"")+(!this.isInset&&this.doNotOverlapAtTop?" listview-do-not-overlap-at-top":"")+(!this.isInset&&this.doNotOverlapAtBottom?" listview-do-not-overlap-at-bottom":"")+'"';if(this.isDividedList&&this.cssClassForDivider)a+=' data-dividertheme="'+this.cssClassForDivider+'"';if(this.isInset)a+=' data-inset="true"';if(this.isCountedList&&this.cssClassForCounter)a+=' data-counttheme="'+this.cssClassForCounter+
'"';if(this.cssClassForSplitView)a+=' data-splittheme="'+this.cssClassForSplitView+'"';if(this.hasSearchBar&&this.usesDefaultSearchBehaviour)a+=' data-filter="true" data-filter-placeholder="'+this.searchBarInitialText+'"';return a},removeListItem:function(a,b,c){var d=M.ViewManager.getViewById(a).modelId;c&&M.EventDispatcher.callHandler(c,b,NO,[a,d])}});
M.DatePickerView=M.View.extend({type:"M.DatePickerView",source:null,callbacks:null,initialDate:null,useSourceDateAsInitialDate:YES,showDatePicker:YES,showTimePicker:YES,showLabels:YES,yearLabel:"Year",monthLabel:"Month",dayLabel:"Day",hoursLabel:"Hours",minutesLabel:"Minutes",showAmPm:YES,startYear:null,endYear:null,dateFormat:"M dd, yy",dateFormatMonthOnly:"MM yy",timeFormat:"h:ii A",dateOrder:"Mddyy",dateOrderMonthOnly:"MMyy",monthNames:["January","February","March","April","May","June","July",
"August","September","October","November","December"],monthNamesShort:["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],dayNames:["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"],dayNamesShort:["Sun","Mon","Tue","Wed","Thu","Fri","Sat"],cancelButtonValue:"Cancel",confirmButtonValue:"Ok",stepHour:1,stepMinute:1,stepSecond:1,seconds:NO,hasSource:YES,isValueSelected:NO,isActive:NO,show:function(a){a=M.DatePickerView.design(a);if(!Object.getPrototypeOf(a).isActive){Object.getPrototypeOf(a).isActive=
YES;if(a.showDatePicker||a.showTimePicker){this.startYear=this.startYear?this.startYear:D8.now().format("yyyy")-20;this.endYear=this.endYear?this.endYear:D8.now().format("yyyy")+20;if(a.source){a.source=typeof a.source==="object"&&a.source.type?a.source.id:a.source;var b=M.ViewManager.getViewById(a.source);b&&typeof b.setValue==="function"&&$("#"+a.source)&&$("#"+a.source).length>0?a.init():M.Logger.log("The specified source for the M.DatepickerView is invalid!",M.ERR)}else{a.hasSource=NO;if(b=M.ViewManager.getCurrentPage()){a.source=
b.id;a.init()}}}else M.Logger.log("In order to use the M.DatepickerView, you have to set the 'showDatePicker' or 'showTimePicker' property to YES.",M.ERR)}},init:function(){var a=this;$("#"+this.source).scroller({preset:this.showDatePicker&&this.showTimePicker?"datetime":this.showDatePicker?"date":this.showTimePicker?"time":null,ampm:this.showAmPm,startYear:this.startYear,endYear:this.endYear,dateFormat:this.dateFormat,timeFormat:this.timeFormat,dateOrder:this.dateOrder,dayText:this.dayLabel,hourText:this.hoursLabel,
minuteText:this.minutesLabel,monthText:this.monthLabel,yearText:this.yearLabel,monthNames:this.monthNames,monthNamesShort:this.monthNamesShort,dayNames:this.dayNames,dayNamesShort:this.dayNamesShort,cancelText:this.cancelButtonValue,setText:this.confirmButtonValue,stepHour:this.stepHour,stepMinute:this.stepMinute,stepSecond:this.stepSecond,seconds:this.seconds,width:(M.Environment.getWidth()-20)/3-20>90?90:(M.Environment.getWidth()-20)/3-20,beforeShow:function(b,c){a.bindToCaller(a,a.beforeShow,[b,
c])()},onClose:function(b,c){a.bindToCaller(a,a.onClose,[b,c])()},onSelect:function(b,c){a.bindToCaller(a,a.onSelect,[b,c])()}});$("#"+this.source).scroller("show")},beforeShow:function(a,b){var c=a=null;if(this.hasSource&&this.useSourceDateAsInitialDate){a=M.ViewManager.getViewById(this.source);if(a.value){try{c=D8.create(a.value)}catch(d){}if(c)if(c.format("yyyy")<this.startYear)if(this.hasOwnProperty("startYear"))M.Logger.log("The given date of the source ("+c.format("yyyy")+") conflicts with the 'startYear' property ("+
this.startYear+") and therefore will be ignored!",M.WARN);else{M.Logger.log("The date picker's default 'startYear' property ("+this.startYear+") conflicts with the given date of the source ("+c.format("yyyy")+") and therefore will be ignored!",M.WARN);$("#"+this.source).scroller("option","startYear",c.format("yyyy"));$("#"+this.source).scroller("setDate",c.date)}else $("#"+this.source).scroller("setDate",c.date)}}if(this.initialDate&&!c){if(this.initialDate.date)c=this.initialDate;else try{c=D8.create(this.initialDate)}catch(e){}if(c)if(c.format("yyyy")<
this.startYear)if(this.hasOwnProperty("startYear"))M.Logger.log("The specified initial date ("+c.format("yyyy")+") conflicts with the 'startYear' property ("+this.startYear+") and therefore will be ignored!",M.WARN);else{M.Logger.log("The date picker's default 'startYear' property ("+this.startYear+") conflicts with the specified initial date ("+c.format("yyyy")+") and therefore will be ignored!",M.WARN);$("#"+this.source).scroller("option","startYear",c.format("yyyy"));$("#"+this.source).scroller("setDate",
c.date)}else $("#"+this.source).scroller("setDate",c.date)}value=b.formatDate(this.showDatePicker?this.dateFormat+(this.showTimePicker?" "+this.timeFormat:""):this.timeFormat,b.getDate());$(".dwv").remove();var f=M.ButtonView.design({value:this.confirmButtonValue,cssClass:"b tmp-dialog-smallerbtn-confirm",events:{tap:{action:function(){$("#dw_set").trigger("click")}}}}),g=M.ButtonView.design({value:this.cancelButtonValue,cssClass:"d tmp-dialog-smallerbtn-confirm",events:{tap:{action:function(){$("#dw_cancel").trigger("click")}}}});
if(this.showDatePicker){f=M.GridView.design({childViews:"confirm cancel",layout:M.TWO_COLUMNS,cssClass:"tmp-datepicker-buttongrid",confirm:f,cancel:g});var h=f.render();$(".dw").append(h);f.theme();f.registerEvents()}else{h=f.render();h+=g.render();$(".dw").append(h);f.theme();f.registerEvents();g.theme();g.registerEvents()}$("#dw_cancel").hide();$("#dw_set").hide();this.showLabels||$("body").addClass("tmp-datepicker-no-label");this.callbacks&&M.EventDispatcher.checkHandler(this.callbacks.before)&&
M.EventDispatcher.callHandler(this.callbacks.before,null,NO,[value,c])},onClose:function(a,b){var c=null,d=null;if(this.isValueSelected){try{d=D8.create(b.getDate())}catch(e){}if(this.hasSource)(c=M.ViewManager.getViewById(this.source))&&c.setValue(a,NO,YES)}this.showLabels||$("body").removeClass("tmp-datepicker-no-label");if(!this.isValueSelected&&this.callbacks&&M.EventDispatcher.checkHandler(this.callbacks.cancel))M.EventDispatcher.callHandler(this.callbacks.cancel,null,NO,[]);else this.isValueSelected&&
this.callbacks&&M.EventDispatcher.checkHandler(this.callbacks.confirm)&&M.EventDispatcher.callHandler(this.callbacks.confirm,null,NO,[a,d]);Object.getPrototypeOf(this).isActive=NO;$("#"+this.source).scroller("destroy");$(".dwo").remove();$(".dw").remove();this.destroy()},onSelect:function(){this.isValueSelected=YES}});
M.LoaderView=M.View.extend({type:"M.LoaderView",isInitialized:NO,refCount:0,defaultTitle:"loading",initialize:function(){if(!this.isInitialized){this.refCount=0;this.isInitialized=YES}},show:function(a){this.refCount++;a=a&&typeof a==="string"?a:this.defaultTitle;if(this.refCount==1){$.mobile.showPageLoadingMsg();this.changeTitle(a);a=$(".ui-loader");var b=M.Environment.getSize(),c=window.pageYOffset,d=a.outerHeight();a.css("top",c+b[1]/2+"px");a.css("margin-top","-"+d/2+"px")}},changeTitle:function(a){$(".ui-loader h1").html(a)},
hide:function(a){if(a||this.refCount<=0)this.refCount=0;else this.refCount--;this.refCount==0&&$.mobile.hidePageLoadingMsg()}});M.HYPERLINK_EMAIL="mail";M.HYPERLINK_WEBSITE="website";M.HYPERLINK_PHONE="phone";
M.LabelView=M.View.extend({type:"M.LabelView",newLineToBreak:YES,tabToSpaces:YES,hyperlinkType:null,hyperlinkTarget:null,recommendedEvents:["tap"],render:function(){this.computeValue();this.html+='<div id="'+this.id+'"'+this.style()+">";if(this.hyperlinkTarget&&this.hyperlinkType)switch(this.hyperlinkType){case M.HYPERLINK_EMAIL:this.html+='<a rel="external" href="mailto:'+this.hyperlinkTarget+'">';break;case M.HYPERLINK_WEBSITE:this.html+='<a rel="external" target="_blank" href="'+this.hyperlinkTarget+
'">';break;case M.HYPERLINK_PHONE:this.html+='<a rel="external" href="tel:'+this.hyperlinkTarget+'">'}this.html+=this.newLineToBreak?this.nl2br(this.tabToSpaces?this.tab2space(this.value):this.value):this.tabToSpaces?this.tab2space(this.value):this.value;if(this.hyperlinkTarget&&this.hyperlinkType)this.html+="</a>";this.html+="</div>";return this.html},renderUpdate:function(){this.computeValue();$("#"+this.id).html(this.newLineToBreak?this.nl2br(this.value):this.value)},style:function(){var a="";
if(this.isInline)a+=' style="display:inline;"';if(this.cssClass)a+=' class="'+this.cssClass+'"';return a},setValue:function(a){this.value=a;this.renderUpdate()}});
M.CanvasView=M.View.extend({type:"M.CanvasView",recommendedEvents:["tap"],render:function(){this.html+='<canvas id="'+this.id+'" ></canvas>';return this.html},renderUpdate:function(){},getCanvas:function(){return $("#"+this.id).get(0)},getContext:function(a){return $("#"+this.id).get(0).getContext(a)},setSize:function(a,b){this.setWidth(a);this.setHeight(b)},setWidth:function(a){$("#"+this.id).get(0).width=a},getWidth:function(){return $("#"+this.id).get(0).width},setHeight:function(a){$("#"+this.id).get(0).height=
a},getHeight:function(){return $("#"+this.id).get(0).height}});M.INPUT_TEXT="text";M.INPUT_PASSWORD="password";M.INPUT_NUMBER="number";M.INPUT_TELEPHONE="tel";M.INPUT_URL="url";M.INPUT_EMAIL="email";M.INPUT_TIME="time";M.INPUT_DATE="date";M.INPUT_MONTH="month";M.INPUT_WEEK="week";M.INPUT_DATETIME="datetime";M.INPUT_DATETIME_LOCAL="datetime-local";
M.TextFieldView=M.View.extend({type:"M.TextFieldView",name:null,label:null,initialText:"",isGrouped:NO,hasMultipleLines:NO,inputType:M.INPUT_TEXT,dateInputTypes:[M.INPUT_DATETIME,M.INPUT_DATE,M.INPUT_MONTH,M.INPUT_WEEK,M.INPUT_TIME,M.INPUT_DATETIME_LOCAL],numberOfChars:null,useNativeImplementationIfAvailable:YES,recommendedEvents:["focus","blur","enter","keyup","tap"],render:function(){this.computeValue();this.html+="<div";if(this.label&&this.isGrouped)this.html+=' data-role="fieldcontain"';if(this.cssClass)this.html+=
' class="'+this.cssClass+'_container"';this.html+=">";if(this.label)this.html+='<label for="'+(this.name?this.name:this.id)+'">'+this.label+"</label>";if(this.hasMultipleLines)this.html+='<textarea cols="40" rows="8" name="'+(this.name?this.name:this.id)+'" id="'+this.id+'"'+this.style()+">"+(this.value?this.value:this.initialText)+"</textarea>";else{var a=this.inputType;if(_.include(this.dateInputTypes,this.inputType)&&!this.useNativeImplementationIfAvailable||this.initialText&&this.inputType==M.INPUT_PASSWORD)a=
"text";this.html+="<input "+(this.numberOfChars?'maxlength="'+this.numberOfChars+'"':"")+'type="'+a+'" name="'+(this.name?this.name:this.id)+'" id="'+this.id+'"'+this.style()+' value="'+(this.value?this.value:this.initialText)+'" />'}this.html+="</div>";return this.html},registerEvents:function(){this.internalEvents={focus:{target:this,action:"gotFocus"},blur:{target:this,action:"lostFocus"},keyup:{target:this,action:"setValueFromDOM"},tap:{target:this,action:"handleTap"}};this.bindToCaller(this,
M.View.registerEvents)()},contentDidChange:function(){if(!this.hasFocus){this.bindToCaller(this,M.View.contentDidChange)();this.renderUpdate();this.delegateValueUpdate()}},renderUpdate:function(a){a||this.computeValue();$("#"+this.id).val(this.value);this.styleUpdate()},handleTap:function(a,b,c){if(_.include(this.dateInputTypes,this.inputType)&&(!M.Environment.supportsInputType(this.inputType)||!this.useNativeImplementationIfAvailable))M.DatePickerView.show({source:this,useSourceDateAsInitialDate:YES,
showDatePicker:this.inputType!==M.INPUT_TIME,showTimePicker:this.inputType===M.INPUT_TIME||this.inputType===M.INPUT_DATETIME||this.inputType===M.INPUT_DATETIME_LOCAL,dateOrder:this.inputType===M.INPUT_MONTH?M.DatePickerView.dateOrderMonthOnly:M.DatePickerView.dateOrder,dateFormat:this.inputType===M.INPUT_MONTH?M.DatePickerView.dateFormatMonthOnly:M.DatePickerView.dateFormat});c&&M.EventDispatcher.callHandler(c,b,YES)},gotFocus:function(a,b,c){if(this.initialText&&(!this.value||this.initialText===
this.value))this.setValue("");this.hasFocus=YES;c&&M.EventDispatcher.callHandler(c,b,YES)},lostFocus:function(a,b,c){_.include(this.dateInputTypes,this.inputType)&&M.Environment.supportsInputType(this.inputType)&&this.useNativeImplementationIfAvailable&&this.setValueFromDOM();if(this.initialText&&!this.value){this.setValue(this.initialText,NO);this.value=""}this.hasFocus=NO;c&&M.EventDispatcher.callHandler(c,b,YES)},style:function(){var a=' style="';if(this.isInline)a+="display:inline;";a+='"';this.isEnabled||
(a+=' disabled="disabled"');if(this.cssClass)a+=' class="'+this.cssClass+'"';return a},theme:function(){this.initialText&&!this.value&&this.cssClassOnInit&&this.addCssClass(this.cssClassOnInit);this.value&&$("#"+this.id).trigger("keyup")},styleUpdate:function(){if(this.value){$("#"+this.id).removeAttr("disabled");$("#"+this.id).trigger("keyup")}this.isInline?$("#"+this.id).attr("display","inline"):$("#"+this.id).removeAttr("display");this.isEnabled?$("#"+this.id).removeAttr("disabled"):$("#"+this.id).attr("disabled",
"disabled")},setValueFromDOM:function(a,b,c){this.value=this.secure($("#"+this.id).val());this.delegateValueUpdate();c&&M.EventDispatcher.callHandler(c,b,YES)},setValue:function(a,b,c){this.value=a;if(a!=this.initialText){this.cssClassOnInit&&this.removeCssClass(this.cssClassOnInit);this.inputType==M.INPUT_PASSWORD&&$("#"+this.id).prop("type","password")}else{this.cssClassOnInit&&this.addCssClass(this.cssClassOnInit);this.inputType==M.INPUT_PASSWORD&&$("#"+this.id).prop("type","text")}this.renderUpdate(c);
b&&this.delegateValueUpdate()},disable:function(){this.isEnabled=NO;this.renderUpdate()},enable:function(){this.isEnabled=YES;this.renderUpdate()},clearValue:function(){this.setValue("");this.lostFocus()},getValue:function(){return this.value}});M.MAP_MARKER_ANIMATION_NONE="NONE";M.MAP_MARKER_ANIMATION_DROP="DROP";M.MAP_MARKER_ANIMATION_BOUNCE="BOUNCE";
M.MapMarkerView=M.View.extend({type:"M.MapMarkerView",marker:null,data:null,map:null,title:null,message:null,showAnnotationOnClick:NO,annotation:null,isDraggable:NO,location:M.Location.extend({latitude:48.813338,longitude:9.178463}),markerAnimationType:null,icon:null,recommendedEvents:["click","tap"],init:function(a){a=this.extend(a);if(a.annotation||a.message){var b=a.title?'<h1 class="ui-annotation-header">'+a.title+"</h1>":"";b+=a.message?'<p class="ui-annotation-message">'+a.message+"</p>":"";
a.annotation=new google.maps.InfoWindow({content:b,maxWidth:100})}return a},registerEvents:function(){this.internalEvents={tap:{target:this,action:"showAnnotation"}};var a=this;google.maps.event.addListener(this.marker,"click",function(){M.EventDispatcher.callHandler(a.internalEvents.tap,event,YES)})},remove:function(){this.map.removeMarker(this)},showAnnotation:function(a,b){this.annotation&&this.annotation.open(this.map.map,this.marker);if(this.events||this.map.events){var c=this.events?this.events:
this.map.events,d;for(d in c)if(d===(b.type==="click"?"tap":b.type))M.EventDispatcher.callHandler(c[d],b,NO,[this])}}});
M.PageView=M.View.extend({type:"M.PageView",isFirstLoad:YES,hasTabBarView:NO,tabBarView:null,recommendedEvents:["pagebeforeshow","pageshow","pagebeforehide","pagehide","orientationchange"],internalEvents:null,listList:null,orientation:null,render:function(){M.ViewManager.currentlyRenderedPage=this;this.html+='<div id="'+this.id+'" data-role="page"'+this.style()+">";this.renderChildViews();this.html+="</div>";this.writeToDOM();this.theme();this.registerEvents()},registerEvents:function(){this.internalEvents=
{pagebeforeshow:{target:this,action:"pageWillLoad"},pageshow:{target:this,action:"pageDidLoad"},pagebeforehide:{target:this,action:"pageWillHide"},pagehide:{target:this,action:"pageDidHide"},orientationchange:{target:this,action:"orientationDidChange"}};this.bindToCaller(this,M.View.registerEvents)()},writeToDOM:function(){if(restartOnBlackBerry)if(document.readyState==="loading")document.write(this.html);else typeof jQuery(this.html)[0]!==undefined&&document.body.innerHTML.indexOf(jQuery(this.html)[0].id)===
-1&&jQuery("body").append(this.html);else document.write(this.html)},pageWillLoad:function(a,b,c){if(M.Application.isFirstLoad){M.Application.isFirstLoad=NO;if((a=M.ViewManager.getCurrentPage())&&a.hasTabBarView){var d=a.tabBarView;if(d.childViews){var e=d.getChildViewsAsArray(),f;for(f in e)M.ViewManager.getPage(d[e[f]].page).id===a.id&&d.setActiveTab(d[e[f]])}}}M.LoaderView&&M.LoaderView.initialize();document.title=M.Application.name;c&&M.EventDispatcher.callHandler(c,b,NO,[this.isFirstLoad])},
pageDidLoad:function(a,b,c){c&&M.EventDispatcher.callHandler(c,b,NO,[this.isFirstLoad]);$.mobile.fixedToolbars.show();this.isFirstLoad=NO},pageWillHide:function(a,b,c){c&&M.EventDispatcher.callHandler(c,b,NO,[this.isFirstLoad])},pageDidHide:function(a,b,c){this.listList&&_.each(this.listList,function(d){d.resetActiveListItem()});c&&M.EventDispatcher.callHandler(c,b,NO,[this.isFirstLoad])},orientationDidChange:function(a,b,c){a=M.Environment.getOrientation();if(a!==this.orientation){$(".tmp-dialog").each(function(){var d=
$(this).attr("id"),e=M.ViewManager.getViewById(d),f=$(this);window.setTimeout(function(){e.positionDialog(f);e.positionBackground($(".tmp-dialog-background"))},500)});this.orientation=a;c&&M.EventDispatcher.callHandler(c,b,NO,[M.Environment.getOrientation()])}},theme:function(){$("#"+this.id).page();this.themeChildViews()},style:function(){var a="";if(this.cssClass){a||(a+=' class="');a+=this.cssClass}if(a)a+='"';return a}});
M.SelectionListItemView=M.View.extend({type:"M.SelectionListItemView",label:null,isSelected:NO,render:function(){if(this.parentView&&(this.parentView.selectionMode===M.SINGLE_SELECTION_DIALOG||this.parentView.selectionMode===M.MULTIPLE_SELECTION_DIALOG)){this.html+='<option id="'+this.id+'" value="'+this.value+'"';if(this.isSelected&&typeof this.isSelected==="boolean"||this.isSelected===String(YES))if(!this.parentView.selection){this.html+=' selected="selected"';this.parentView.selection=this}this.html+=
">";this.html+=this.label?this.label:this.value;this.html+="</option>"}else{this.html+='<input type="'+this.parentView.selectionMode+'" data-native-menu="false" id="'+this.id+'"';if(this.parentView.selectionMode===M.SINGLE_SELECTION)this.html+=' name="'+(this.parentView.name?this.parentView.name:this.parentView.id)+'"';else if(this.parentView.selectionMode===M.MULTIPLE_SELECTION)this.html+=' name="'+(this.name?this.name:this.id)+'"';if(this.isSelected&&typeof this.isSelected==="boolean"||this.isSelected===
String(YES))if(this.parentView.selectionMode===M.SINGLE_SELECTION){if(!this.parentView.selection){this.html+=' checked="checked"';this.parentView.selection=this}}else{this.html+=' checked="checked"';if(!this.parentView.selection)this.parentView.selection=[];this.parentView.selection.push(this)}this.html+="/>";this.html+='<label for="'+this.id+'">'+(this.label?this.label:this.value)+"</label>"}return this.html},theme:function(){this.parentView&&this.parentView.selectionMode!==M.SINGLE_SELECTION_DIALOG&&
this.parentView.selectionMode!==M.MULTIPLE_SELECTION_DIALOG&&$("#"+this.id).checkboxradio()}});M.SINGLE_SELECTION="radio";M.MULTIPLE_SELECTION="checkbox";M.SINGLE_SELECTION_DIALOG="select";M.MULTIPLE_SELECTION_DIALOG="select_multiple";m_require("ui/selection_list_item.js");
M.SelectionListView=M.View.extend({type:"M.SelectionListView",removeItemsOnUpdate:YES,selectionMode:M.SINGLE_SELECTION,selection:null,name:null,initialText:null,label:null,isGrouped:NO,initialState:null,recommendedEvents:["change"],render:function(){this.initialState=[];this.html+='<div id="'+this.id+'_container"';if(this.isGrouped)this.html+=' data-role="fieldcontain"';if(this.cssClass){this.html+=' class="';var a=$.trim(this.cssClass).split(" "),b;for(b in a)this.html+=(b>0?" ":"")+a[b]+"_container";
this.html+='"'}this.html+=">";if(this.selectionMode===M.SINGLE_SELECTION_DIALOG||this.selectionMode===M.MULTIPLE_SELECTION_DIALOG){if(this.label)this.html+='<label for="'+this.id+'">'+this.label+"</label>";this.html+='<select name="'+(this.name?this.name:this.id)+'" id="'+this.id+'"'+this.style()+(this.selectionMode===M.MULTIPLE_SELECTION_DIALOG?' multiple="multiple"':"")+">";this.renderChildViews();this.html+="</select>"}else{this.html+='<fieldset data-role="controlgroup" data-native-menu="false" id="'+
this.id+'">';if(this.label)this.html+="<legend>"+this.label+"</legend>";this.renderChildViews();this.html+="</fieldset>"}this.html+="</div>";return this.html},renderChildViews:function(){if(this.childViews){var a=this.getChildViewsAsArray(),b;for(b in a){var c=this[a[b]];if(c.type==="M.SelectionListItemView"){c.parentView=this;c._name=a[b];this.html+=c.render();this.initialState.push({value:c.value,label:c.label,isSelected:c.isSelected})}else M.Logger.log("Invalid child views specified for SelectionListView. Only SelectionListItemViews accepted.",
M.WARN)}}else this.contentBinding||M.Logger.log("No SelectionListItemViews specified.",M.WARN)},registerEvents:function(){this.internalEvents={change:{target:this,action:"itemSelected"}};this.bindToCaller(this,M.View.registerEvents)()},addItem:function(a){$("#"+this.id).append(a)},removeAllItems:function(){$("#"+this.id).empty()},renderUpdate:function(){if(this.removeItemsOnUpdate||this.selectionMode===M.SINGLE_SELECTION_DIALOG||this.selectionMode===M.MULTIPLE_SELECTION_DIALOG){this.removeAllItems();
if(this.label&&!(this.selectionMode===M.SINGLE_SELECTION_DIALOG||this.selectionMode===M.MULTIPLE_SELECTION_DIALOG))this.addItem("<legend>"+this.label+"</legend>")}this.removeSelection();if(this.contentBinding){var a=this.value,b;for(b in a){var c=a[b],d=null;d=M.SelectionListItemView.design({value:c.value!==undefined&&c.value!==null?c.value:"",label:c.label?c.label:c.value!==undefined&&c.value!==null?c.value:"",parentView:this,isSelected:c.isSelected});if(this.selectionMode!==M.SINGLE_SELECTION_DIALOG&&
this.selectionMode!==M.MULTIPLE_SELECTION_DIALOG)d.name=c.name?c.name:c.label?c.label:c.value?c.value:"";this.addItem(d.render());d.theme()}this.themeUpdate()}},theme:function(){if(this.selectionMode===M.SINGLE_SELECTION_DIALOG||this.selectionMode===M.MULTIPLE_SELECTION_DIALOG){$("#"+this.id).selectmenu();this.selectionMode===M.MULTIPLE_SELECTION_DIALOG&&this.initialText&&this.selection&&this.selection.length===0&&$("#"+this.id+"_container").find(".ui-btn-text").html(this.initialText)}else this.selectionMode!==
M.SINGLE_SELECTION_DIALOG&&this.selectionMode!==M.MULTIPLE_SELECTION_DIALOG&&$("#"+this.id).controlgroup()},themeUpdate:function(){if(this.selectionMode===M.SINGLE_SELECTION_DIALOG||this.selectionMode===M.MULTIPLE_SELECTION_DIALOG){$("#"+this.id).selectmenu("refresh");if(this.selectionMode===M.MULTIPLE_SELECTION_DIALOG&&this.initialText&&this.selection&&this.selection.length===0)$("#"+this.id+"_container").find(".ui-btn-text").html(this.initialText);else if(this.selectionMode===M.SINGLE_SELECTION_DIALOG&&
!this.selection){var a=M.ViewManager.getViewById($("#"+this.id).find("option:first-child").attr("id"));a!==undefined&&a!==null&&this.setSelection(a.value)}}else this.selectionMode!==M.SINGLE_SELECTION_DIALOG&&this.selectionMode!==M.MULTIPLE_SELECTION_DIALOG&&$("#"+this.id).controlgroup()},style:function(){var a="";if(this.cssClass)a+=' class="'+this.cssClass+'"';return a},itemSelected:function(a,b,c){a=null;if(this.selectionMode===M.SINGLE_SELECTION){a=M.ViewManager.getViewById($("input[name="+(this.name?
this.name:this.id)+"]:checked").attr("id"));if(a!==this.selection){this.selection=a;c&&M.EventDispatcher.callHandler(c,b,NO,[this.selection.value,this.selection])}}else if(this.selectionMode===M.SINGLE_SELECTION_DIALOG){a=M.ViewManager.getViewById($("#"+this.id+" :selected").attr("id"));if(a!==this.selection){this.selection=a;$("#"+this.id+"_container").find(".ui-btn-text").html(a.label?a.label:a.value);c&&M.EventDispatcher.callHandler(c,b,NO,[this.selection.value,this.selection])}}else if(this.selectionMode===
M.MULTIPLE_SELECTION){var d=this;this.selection=[];$("#"+this.id).find("input:checked").each(function(){d.selection.push(M.ViewManager.getViewById($(this).attr("id")))});a=[];for(var e in this.selection)a.push(this.selection[e].value);c&&M.EventDispatcher.callHandler(c,b,NO,[a,this.selection])}else if(this.selectionMode===M.MULTIPLE_SELECTION_DIALOG){d=this;this.selection=[];$("#"+this.id).find(":selected").each(function(){d.selection.push(M.ViewManager.getViewById($(this).attr("id")))});a=[];for(e in this.selection){a.push(this.selection[e].value);
$("#"+this.id+"_container").find(".ui-btn-text").html(this.formatSelectionLabel(this.selection.length))}this.selection.length===0&&this.themeUpdate();c&&M.EventDispatcher.callHandler(c,b,NO,[a,this.selection])}},getSelection:function(a){if(this.selectionMode===M.SINGLE_SELECTION||this.selectionMode===M.SINGLE_SELECTION_DIALOG){if(this.selection)return a?this.selection:this.selection.value}else{if(this.selection){var b=[];_.each(this.selection,function(c){a?b.push(c):b.push(c.value)});return b}return[]}},
setSelection:function(a){var b=this;if(this.selectionMode===M.SINGLE_SELECTION&&(typeof a==="string"||typeof a==="number"||typeof a==="boolean"))$("#"+this.id).find("input").each(function(){var e=M.ViewManager.getViewById($(this).attr("id"));if(e.value==a){b.removeSelection();e.isSelected=YES;b.selection=e;$(this).attr("checked","checked");$(this).siblings("label:first").addClass("ui-radio-on");$(this).siblings("label:first").removeClass("ui-radio-off");$(this).siblings("label:first").find("span .ui-icon-radio-off").addClass("ui-icon-radio-on");
$(this).siblings("label:first").find("span .ui-icon-radio-off").removeClass("ui-icon-radio-off")}});else if(this.selectionMode===M.SINGLE_SELECTION_DIALOG&&(typeof a==="string"||typeof a==="number"||typeof a==="boolean")){var c=NO;$("#"+this.id).find("option").each(function(){var e=M.ViewManager.getViewById($(this).attr("id"));if(e.value==a){b.removeSelection();e.isSelected=YES;b.selection=e;$("#"+b.id).val(e.value);c=YES}});c&&$("#"+this.id).selectmenu("refresh")}else if(typeof a==="object")if(this.selectionMode===
M.MULTIPLE_SELECTION){var d=NO;$("#"+this.id).find("input").each(function(){var e=M.ViewManager.getViewById($(this).attr("id")),f;for(f in a)if(e.value==a[f]){if(!d){b.removeSelection();d=YES}e.isSelected=YES;b.selection.push(e);$(this).attr("checked","checked");$(this).siblings("label:first").removeClass("ui-checkbox-off");$(this).siblings("label:first").addClass("ui-checkbox-on");$(this).siblings("label:first").find("span .ui-icon-checkbox-off").addClass("ui-icon-checkbox-on");$(this).siblings("label:first").find("span .ui-icon-checkbox-off").removeClass("ui-icon-checkbox-off")}})}else if(this.selectionMode===
M.MULTIPLE_SELECTION_DIALOG){d=NO;$("#"+this.id).find("option").each(function(){var e=M.ViewManager.getViewById($(this).attr("id")),f;for(f in a)if(e.value==a[f]){if(!d){b.removeSelection();d=YES}e.isSelected=YES;b.selection.push(e);$(this).attr("selected","selected")}$("#"+b.id+"_container").find(".ui-btn-text").html(b.formatSelectionLabel(b.selection.length))})}b.theme()},removeSelection:function(){var a=this;this.selection=this.selectionMode===M.SINGLE_SELECTION||this.selectionMode===M.SINGLE_SELECTION_DIALOG?
null:[];if(this.selectionMode!==M.SINGLE_SELECTION_DIALOG&&this.selectionMode!==M.MULTIPLE_SELECTION_DIALOG)$("#"+this.id).find("input").each(function(){M.ViewManager.getViewById($(this).attr("id")).isSelected=NO;$(this).removeAttr("checked");$(this).siblings("label:first").addClass("ui-"+a.selectionMode+"-off");$(this).siblings("label:first").removeClass("ui-"+a.selectionMode+"-on");$(this).siblings("label:first").find("span .ui-icon-"+a.selectionMode+"-on").addClass("ui-icon-"+a.selectionMode+"-off");
$(this).siblings("label:first").find("span .ui-icon-"+a.selectionMode+"-on").removeClass("ui-icon-"+a.selectionMode+"-on")});else{$("#"+this.id).find("option").each(function(){M.ViewManager.getViewById($(this).attr("id")).isSelected=NO});$("#"+this.id).val("").removeAttr("checked").removeAttr("selected")}},resetSelection:function(){if(this.contentBinding){this.removeSelection();this.renderUpdate()}else{this.contentBinding={};this.contentBinding.target=this;this.contentBinding.property="initialState";
this.removeSelection();this.renderUpdate();this.contentBinding=null}},clearValue:function(){this.resetSelection()},getValue:function(){return this.getSelection()},formatSelectionLabel:function(a){return a+" Object(s)"},disable:function(){this.isEnabled=NO;if(this.selectionMode===M.SINGLE_SELECTION||this.selectionMode===M.MULTIPLE_SELECTION)$("#"+this.id).find("input").each(function(){$(this).checkboxradio("disable")});else{$("#"+this.id).select("disable");$("#"+this.id).each(function(){$(this).attr("disabled",
"disabled")})}},enable:function(){this.isEnabled=YES;if(this.selectionMode===M.SINGLE_SELECTION||this.selectionMode===M.MULTIPLE_SELECTION)$("#"+this.id).find("input").each(function(){$(this).checkboxradio("enable")});else{$("#"+this.id).select("enable");$("#"+this.id).each(function(){$(this).removeAttr("disabled")})}}});
M.ScrollView=M.View.extend({type:"M.ScrollView",render:function(){this.html+='<div id="'+this.id+'" data-role="content"'+this.style()+">";this.renderChildViews();this.html+="</div>";return this.html},style:function(){var a="";if(this.cssClass)a+=' class="'+this.cssClass+'"';return a}});
M.ButtonView=M.View.extend({type:"M.ButtonView",isActive:NO,isIconOnly:NO,hyperlinkType:null,hyperlinkTarget:null,tag:null,recommendedEvents:["click","tap"],render:function(){this.computeValue();this.html+='<a data-role="button" id="'+this.id+'"'+this.style()+" ";if(this.hyperlinkTarget&&this.hyperlinkType)switch(this.hyperlinkType){case M.HYPERLINK_EMAIL:this.html+='rel="external" href="mailto:'+this.hyperlinkTarget+'"';break;case M.HYPERLINK_WEBSITE:this.html+='rel="external" target="_blank" href="'+
this.hyperlinkTarget+'"';break;case M.HYPERLINK_PHONE:this.html+='rel="external" href="tel:'+this.hyperlinkTarget+'"'}else this.html+='href="#"';this.html+=">"+this.value+"</a>";return this.html},registerEvents:function(){if(!this.internalEvents)this.internalEvents={tap:{target:this,action:"dispatchEvent"}};this.bindToCaller(this,M.View.registerEvents)()},renderUpdate:function(){this.computeValue();this.parentView&&this.parentView.type==="M.ButtonGroupView"?$("#"+this.id).find(".ui-btn-text").text(this.value):
$("#"+this.id).parent().find(".ui-btn-text").text(this.value)},setValue:function(a){this.value=a;this.renderUpdate()},theme:function(){$("#"+this.id).hasClass("ui-btn")||$("#"+this.id).button()},style:function(){var a="";if(this.isInline)a+=' data-inline="true"';if(this.icon)a+=' data-icon="'+this.icon+'"';if(this.cssClass)a+=' data-theme="'+this.cssClass+'"';if(this.isIconOnly)a+=' data-iconpos="notext"';if(this.cssStyle)a+='style="'+this.cssStyle+'"';return a},dispatchEvent:function(a,b,c){this.isEnabled&&
c&&M.EventDispatcher.callHandler(c,b,YES)},disable:function(){if(this.isEnabled){var a=$("#"+this.id).html();a='<div data-theme="c" class="ui-shadow ui-disabled" aria-disabled="true">'+a+"</div>";$("#"+this.id).html(a);this.isEnabled=NO}},enable:function(){if(!this.isEnabled){var a=$("#"+this.id+" div").html();$("#"+this.id).html(a);this.isEnabled=YES}}});m_require("ui/button.js");
M.ListItemView=M.View.extend({type:"M.ListItemView",inEditMode:NO,hasSingleAction:YES,deleteButton:M.ButtonView.design({icon:"delete",value:""}),isDivider:NO,recommendedEvents:["tap"],isSelectable:YES,render:function(){this.html='<li id="'+this.id+'"'+this.style();if(this.isDivider)this.html+=' data-role="list-divider"';this.html+=">";if(this.childViews)if(this.inEditMode){this.html+='<a href="#">';this.renderChildViews();this.html+="</a>";this.html+=this.deleteButton.render()}else if(this.isSelectable){this.html+=
'<a href="#">';this.renderChildViews();this.html+="</a>"}else this.renderChildViews();else if(this.value)this.html+=this.value;this.html+="</li>";return this.html},registerEvents:function(){this.internalEvents={tap:{target:this.parentView,action:"setActiveListItem"}};this.bindToCaller(this,M.View.registerEvents)()},style:function(){var a="";if(this.cssClass)a+=' class="'+this.cssClass+'"';return a}});
M.TabBarItemView=M.View.extend({type:"M.TabBarItemView",isActive:NO,recommendedEvents:["click","tap"],render:function(){this.html="";this.id=this.id.lastIndexOf("_")==1?this.id+"_"+this.parentView.usageCounter:this.id.substring(0,this.id.lastIndexOf("_"))+"_"+this.parentView.usageCounter;M.ViewManager.register(this);this.html+='<li><a id="'+this.id+'"'+this.style()+' href="#">'+this.value+"</a></li>";return this.html},registerEvents:function(){this.internalEvents={tap:{target:this,action:"switchPage"}};
this.bindToCaller(this,M.View.registerEvents)()},switchPage:function(){this.page?M.Controller.switchToTab(this):this.parentView.setActiveTab(this)},style:function(){var a="";if(this.cssClass)a+=' class="'+this.cssClass+'"';if(this.isActive){a+=a!=""?"":' class="';a+="ui-btn-active";a+='"'}if(this.icon){a+=' data-icon="';a+=this.icon;a+='" data-iconpos="top"'}return a}});
M.TabBarView=M.View.extend({type:"M.TabBarView",anchorLocation:null,name:"tab_bar",activeTab:null,usageCounter:0,render:function(){this.html="";this.usageCounter+=1;this.html+=this.anchorLocation?'<div id="'+this.id+'" data-id="'+this.name+'" data-role="'+this.anchorLocation+'" data-position="fixed"><div data-role="navbar"><ul>':'<div data-role="navbar" id="'+this.id+'" data-id="'+this.name+'"><ul>';this.renderChildViews();this.html+="</ul></div>";if(this.anchorLocation)this.html+="</div>";return this.html},
renderChildViews:function(){if(this.childViews){var a=this.getChildViewsAsArray(),b=NO,c;for(c in a){var d=this[a[c]];if(d.type==="M.TabBarItemView"&&d.isActive)if(b)d.isActive=NO;else{b=YES;this.activeTab=d}}var e=0;for(c in a){d=this[a[c]];if(d.type==="M.TabBarItemView"){e+=1;if(e===1&&!b){d.isActive=YES;this.activeTab=d}d.parentView=this;d._name=a[c];this.html+=d.render()}else M.Logger.log("Invalid child views specified for TabBarView. Only TabBarItemViews accepted.",M.WARN)}}else M.Logger.log("No TabBarItemViews specified.",
M.WARN)},setActiveTab:function(a){this.activeTab.isActive=NO;var b=this.activeTab.id.substring(0,this.activeTab.id.lastIndexOf("_"));$("[id^="+b+"_]").each(function(){$(this).removeClass("ui-btn-active")});a.isActive=YES;this.activeTab=a;a=a.id.substring(0,a.id.lastIndexOf("_"));$("[id^="+a+"_]").each(function(){$(this).addClass("ui-btn-active")})}});
M.ImageView=M.View.extend({type:"M.ImageView",recommendedEvents:["click","tap","error","load"],render:function(){this.computeValue();this.html+='<img id="'+this.id+'" src="'+(this.value&&typeof this.value==="string"?this.value:"")+'"'+this.style()+">";return this.html},registerEvents:function(){this.internalEvents={error:{target:this,action:"sourceIsInvalid"},load:{target:this,action:"sourceIsValid"}};this.bindToCaller(this,M.View.registerEvents)()},renderUpdate:function(){this.computeValue();$("#"+
this.id).attr("src",this.value)},theme:function(){},style:function(){var a="";if(this.cssClass)a+=' class="'+this.cssClass+'"';return a},sourceIsInvalid:function(a,b,c){M.Logger.log("The source '"+this.value+"' is invalid, so we hide the image!",M.WARN);$("#"+this.id).hide();c&&M.EventDispatcher.callHandler(c,b,YES)},sourceIsValid:function(a,b,c){$("#"+this.id).show();c&&M.EventDispatcher.callHandler(c,b,YES)}});
M.DashboardView=M.View.extend({type:"M.DashboardView",itemsPerLine:3,recommendedEvents:["click","tap"],items:[],isEditable:NO,isInEditMode:NO,name:"dashboard",touchPositions:null,latestTouchEventType:null,render:function(){this.html+='<div id="'+this.id+'"'+this.style()+">";this.renderChildViews();this.html+="</div>";this.html+='<div class="tmp-dashboard-line-clear"></div>';this.touchPositions={};return this.html},renderChildViews:function(){if(this.childViews){var a=this.getChildViewsAsArray(),b;
for(b in a){this[a[b]].parentView=this;this[a[b]]._name=a[b];this.html+=this.renderDashboardItemView(this[a[b]],b)}}},renderUpdate:function(){if(this.contentBinding){this.removeAllItems();var a=localStorage.getItem(M.LOCAL_STORAGE_PREFIX+M.Application.name+M.LOCAL_STORAGE_SUFFIX+"dashboard");a=a?JSON.parse(a):null;this.items=[];a=a&&this.value&&a.length==this.value.length?this.sortItemsByValues(this.value,a):this.value;var b="",c;for(c in a)b+=this.renderDashboardItemView(a[c],c);this.addItems(b);
for(c in this.items)this.items[c].registerEvents()}},addItems:function(a){$("#"+this.id).append(a)},removeAllItems:function(){$("#"+this.id).empty()},renderDashboardItemView:function(a){if(a&&a.value&&a.icon){a=a.type==="M.DashboardItemView"?a:M.DashboardItemView.design({value:a.value?a.value:"",icon:a.icon?a.icon:"",label:a.label?a.label:a.value?a.value:"",parentView:this,events:a.events});var b="";this.items.push(a);a.cssStyle="width: "+100/this.itemsPerLine+"%";b+=a.render();return b}else M.Logger.log("Childview of dashboard is no valid dashboard item.",
M.WARN)},dispatchTapEvent:function(a,b,c){c&&M.EventDispatcher.callHandler(c,b,YES);this.events&&this.events.tap&&M.EventDispatcher.callHandler(this.events.tap,b,YES);this.latestTapEventTimestamp=+new Date},editDashboard:function(a,b){this.touchPositions.touchstart={};if(!(!this.isEditable||this.latestTapEventTimestamp>+new Date-500))if(this.isInEditMode&&b)this.stopEditMode();else if(!this.isInEditMode&&b||this.isInEditMode&&!b){M.EventDispatcher.unregisterEvents(this.id);this.isInEditMode=YES;_.each(this.items,
function(c){c.addCssClass("rotate"+M.Math.random(1,2));M.EventDispatcher.unregisterEvents(c.id);if($.support.touch){M.EventDispatcher.registerEvent("touchstart",c.id,{target:c.parentView,action:"editTouchStart"},c.recommendedEvents);M.EventDispatcher.registerEvent("touchend",c.id,{target:c.parentView,action:"editTouchEnd"},c.recommendedEvents);M.EventDispatcher.registerEvent("touchmove",c.id,{target:c.parentView,action:"editTouchMove"},c.recommendedEvents)}else{M.EventDispatcher.registerEvent("mousedown",
c.id,{target:c.parentView,action:"editMouseDown"},c.recommendedEvents);M.EventDispatcher.registerEvent("mouseup",c.id,{target:c.parentView,action:"editMouseUp"},c.recommendedEvents)}})}},stopEditMode:function(){this.isInEditMode=NO;_.each(this.items,function(a){a.removeCssClass("rotate1");a.removeCssClass("rotate2");M.EventDispatcher.unregisterEvents(a.id);a.registerEvents()})},setValue:function(a){this.value=a;var b=[];_.each(a,function(c){b.push(c.value)});localStorage&&localStorage.setItem(M.LOCAL_STORAGE_PREFIX+
M.Application.name+M.LOCAL_STORAGE_SUFFIX+"dashboard",JSON.stringify(b))},sortItemsByValues:function(a,b){var c=[];_.each(b,function(d){_.each(a,function(e){e.value===d&&c.push(e)})});return c},editTouchStart:function(a,b){this.latestTouchEventType="touchstart";var c=b.originalEvent?b.originalEvent.changedTouches?b.originalEvent.changedTouches[0]:null:null;this.touchPositions.touchstart={x:c.clientX,y:c.clientY,date:+new Date};var d=this;window.setTimeout(function(){d.latestTouchEventType==="touchstart"&&
d.stopEditMode()},750)},editTouchMove:function(a,b){this.latestTouchEventType="touchmove";var c=b.originalEvent?b.originalEvent.changedTouches?b.originalEvent.changedTouches[0]:null:null;if(c){var d=c.pageX-parseInt($("#"+a).css("width"))/2;c=c.pageY-parseInt($("#"+a).css("height"))/2;$("#"+a).css("position","absolute");$("#"+a).css("left",d+"px");$("#"+a).css("top",c+"px")}},editTouchEnd:function(a,b){this.latestTouchEventType="touchend";if(b.currentTarget.id){var c=[];_.each(this.items,function(e){c.push({id:e.id,
x:$("#"+e.id).position().left,y:$("#"+e.id).position().top,item:e});c.sort(function(f,g){return Math.abs(f.y-g.y)<30?f.x<g.x?-1:1:f.y<g.y?-1:1})});var d=[];_.each(c,function(e){d.push(e.item)});this.setValue(d);this.renderUpdate();this.isInEditMode&&this.editDashboard()}},editMouseDown:function(a,b){this.latestTouchEventType="mousedown";this.touchPositions.touchstart={x:b.clientX,y:b.clientY,date:+new Date};M.EventDispatcher.registerEvent("mousemove",a,{target:this,action:"editMouseMove"},M.ViewManager.getViewById(a).recommendedEvents);
var c=this;window.setTimeout(function(){c.latestTouchEventType==="mousedown"&&c.stopEditMode()},750)},editMouseMove:function(a,b){this.latestTouchEventType="mousemove";var c=b.pageX-parseInt($("#"+a).css("width"))/2,d=b.pageY-parseInt($("#"+a).css("height"))/2;$("#"+a).css("position","absolute");$("#"+a).css("left",c+"px");$("#"+a).css("top",d+"px")},editMouseUp:function(a,b){this.latestTouchEventType="mouseup";if(b.currentTarget.id){var c=[];_.each(this.items,function(e){M.EventDispatcher.unregisterEvent("mousemove",
e.id);c.push({id:e.id,x:$("#"+e.id).position().left,y:$("#"+e.id).position().top,item:e});c.sort(function(f,g){return Math.abs(f.y-g.y)<30?f.x<g.x?-1:1:f.y<g.y?-1:1})});var d=[];_.each(c,function(e){d.push(e.item)});this.setValue(d);this.renderUpdate();this.isInEditMode&&this.editDashboard()}},style:function(){var a="";if(this.cssClass)a+=' class="tmp-dashboard '+this.cssClass+'"';return a}});M.TWO_COLUMNS={cssClass:"ui-grid-a",columns:{0:"ui-block-a",1:"ui-block-b"}};
M.THREE_COLUMNS={cssClass:"ui-grid-b",columns:{0:"ui-block-a",1:"ui-block-b",2:"ui-block-c"}};M.FOUR_COLUMNS={cssClass:"ui-grid-c",columns:{0:"ui-block-a",1:"ui-block-b",2:"ui-block-c",3:"ui-block-d"}};
M.GridView=M.View.extend({type:"M.GridView",layout:null,render:function(){this.html+='<div id="'+this.id+'" '+this.style()+">";this.renderChildViews();this.html+="</div>";return this.html},renderChildViews:function(){if(this.childViews)if(this.layout){var a=this.childViews.split(" "),b;for(b in this.layout.columns)if(this[a[b]]){this.html+='<div class="'+this.layout.columns[b]+'">';this[a[b]]._name=a[b];this.html+=this[a[b]].render();this.html+="</div>"}}else M.Logger.log("No layout specified for GridView ("+
this.id+")!",M.WARN)},theme:function(){this.themeChildViews()},style:function(){if(this.layout)return'class="'+this.layout.cssClass+'"'}});M.MAP_ROADMAP="ROADMAP";M.MAP_HYBRID="HYBRID";M.MAP_SATELLITE="SATELLITE";M.MAP_TERRAIN="TERRAIN";M.INITIAL_MAP=null;
M.MapView=M.View.extend({type:"M.MapView",map:null,markers:null,isInset:YES,zoomLevel:15,mapType:M.MAP_ROADMAP,showMapTypeControl:NO,showNavigationControl:NO,showStreetViewControl:NO,isDraggable:YES,initialLocation:M.Location.extend({latitude:48.813338,longitude:9.178463}),setMarkerAtInitialLocation:NO,markerAnimationType:M.MAP_MARKER_ANIMATION_NONE,isInitialized:NO,removeMarkersOnUpdate:YES,callbacks:null,loadPlacesLibrary:YES,recommendedEvents:["click","tap"],render:function(){this.html+='<div data-fullscreen="true" id="'+
this.id+'"';this.html+=!this.isInset?' class="ui-listview"':"";this.html+='><div id="'+this.id+'_map"'+this.style()+"></div></div>";return this.html},renderUpdate:function(){var a=null;if(this.contentBinding&&this.contentBinding.target&&typeof this.contentBinding.target==="object"&&this.contentBinding.property&&typeof this.contentBinding.property==="string"&&this.contentBinding.target[this.contentBinding.property]){a=this.contentBinding.target[this.contentBinding.property];var b=[],c=this;if(a&&a[0]&&
a[0].type==="M.Location")_.each(a,function(d){d&&typeof d==="object"&&d.type==="M.Location"&&b.push(M.MapMarkerView.init({location:d,map:c}))});else if(a&&a[0]&&a[0].type==="M.MapMarkerView")b=_.select(a,function(d){return d&&d.type==="M.MapMarkerView"});this.removeMarkersOnUpdate&&this.removeAllMarkers();_.each(b,function(d){c.addMarker(d)})}else M.Logger.log("No valid content binding specified for M.MapView ("+this.id+")!",M.WARN)},registerEvents:function(){},style:function(){var a="";if(this.cssClass)a+=
' class="'+this.cssClass+'"';return a},initMap:function(a,b){if(!this.isInitialized||b){if(!b)this.markers=[];if(typeof google==="undefined"){M.INITIAL_MAP={map:this,options:a,isUpdate:b};M.Environment.getConnectionStatus({target:this,action:"didRetrieveConnectionStatus"})}else this.googleDidLoad(a,b,true)}else M.Logger.log("The M.MapView has already been initialized",M.WARN)},didRetrieveConnectionStatus:function(a){if(a===M.ONLINE)$.getScript("http://maps.google.com/maps/api/js?"+(this.loadPlacesLibrary?
"libraries=places&":"")+"sensor=true&callback=M.INITIAL_MAP.map.googleDidLoad");else(a=M.INITIAL_MAP.options?M.INITIAL_MAP.options.callbacks:null)&&M.EventDispatcher.checkHandler(a.error)&&this.bindToCaller(a.error.target,a.error.action)()},googleDidLoad:function(a,b,c){if(!c){a=M.INITIAL_MAP.options;b=M.INITIAL_MAP.isUpdate}for(var d in a)switch(d){case "zoomLevel":this[d]=typeof a[d]==="number"&&a[d]>0?a[d]>22?22:a[d]:this[d];break;case "mapType":this[d]=a[d]===M.MAP_ROADMAP||a[d]===M.MAP_HYBRID||
a[d]===M.MAP_SATELLITE||a[d]===M.MAP_TERRAIN?a[d]:this[d];break;case "markerAnimationType":this[d]=a[d]===M.MAP_MARKER_ANIMATION_BOUNCE||a[d]===M.MAP_MARKER_ANIMATION_DROP?a[d]:this[d];break;case "showMapTypeControl":case "showNavigationControl":case "showStreetViewControl":case "isDraggable":case "setMarkerAtInitialLocation":case "removeMarkersOnUpdate":this[d]=typeof a[d]==="boolean"?a[d]:this[d];break;case "initialLocation":this[d]=typeof a[d]==="object"&&a[d].type==="M.Location"?a[d]:this[d];
break;case "callbacks":this[d]=typeof a[d]==="object"?a[d]:this[d]}if(b){this.removeMarkersOnUpdate&&this.removeAllMarkers();this.map.setOptions({zoom:this.zoomLevel,center:new google.maps.LatLng(this.initialLocation.latitude,this.initialLocation.longitude),mapTypeId:google.maps.MapTypeId[this.mapType],mapTypeControl:this.showMapTypeControl,navigationControl:this.showNavigationControl,streetViewControl:this.showStreetViewControl,draggable:this.isDraggable})}else this.map=new google.maps.Map($("#"+
this.id+"_map")[0],{zoom:this.zoomLevel,center:new google.maps.LatLng(this.initialLocation.latitude,this.initialLocation.longitude),mapTypeId:google.maps.MapTypeId[this.mapType],mapTypeControl:this.showMapTypeControl,navigationControl:this.showNavigationControl,streetViewControl:this.showStreetViewControl,draggable:this.isDraggable});this.setMarkerAtInitialLocation&&this.addMarker(M.MapMarkerView.init({location:this.initialLocation,map:this.map}));this.isInitialized=YES;!b&&this.callbacks.success&&
M.EventDispatcher.checkHandler(this.callbacks.success)&&this.bindToCaller(this.callbacks.success.target,this.callbacks.success.action)()},updateMap:function(a){this.initMap(a,YES)},addMarker:function(a){if(a&&typeof a==="object"&&a.type==="M.MapMarkerView"){a.marker=new google.maps.Marker({map:this.map,draggable:NO,animation:google.maps.Animation[a.markerAnimationType?a.markerAnimationType:this.markerAnimationType],position:new google.maps.LatLng(a.location.latitude,a.location.longitude),icon:a.icon});
a.registerEvents();this.markers.push(a)}else M.Logger.log("No valid M.MapMarkerView passed for addMarker().",M.WARN)},removeMarker:function(a){if(a&&typeof a==="object"&&a.type==="M.MapMarkerView"){var b=NO;this.markers=_.select(this.markers,function(c){if(a===c){c.marker.setMap(null);b=YES}return a!==c});b||M.Logger.log("No marker found matching the passed marker in removeMarker().",M.WARN)}else M.Logger.log("No valid M.MapMarkerView passed for removeMarker().",M.WARN)},removeAllMarkers:function(){_.each(this.markers,
function(a){a.marker.setMap(null)});this.markers=[]}});M.TOP="header";M.BOTTOM="footer";M.LEFT="LEFT";M.CENTER="CENTER";M.RIGHT="RIGHT";
M.ToolbarView=M.View.extend({type:"M.ToolbarView",anchorLocation:M.TOP,showBackButton:NO,backButton:null,isFixed:YES,render:function(){this.html+='<div id="'+this.id+'" data-role="'+this.anchorLocation+'"'+this.style();if(this.isFixed)this.html+=' data-position="fixed"';this.html+=">";this.renderChildViews();this.html+="</div>";return this.html},renderChildViews:function(){if(this.value&&this.showBackButton){this.backButton=M.ButtonView.design({value:"Back",icon:"arrow-l",internalEvents:{tap:{action:function(){history.back(-1)}}}});
this.html+='<div class="ui-btn-left">';this.html+=this.backButton.render();this.html+="</div>";this.html+="<h1>"+this.value+"</h1>"}else if(this.value)this.html+="<h1>"+this.value+"</h1>";else if(this.childViews){var a=this.getChildViewsAsArray(),b={},c;for(c in a){var d=this[a[c]];d._name=a[c];if(b[d.anchorLocation]){M.Logger.log("ToolbarView has two items positioned at M."+d.anchorLocation+".  Only one item permitted in each location",M.WARN);break}b[d.anchorLocation]=YES;switch(d.anchorLocation){case M.LEFT:this.html+=
'<div class="ui-btn-left">';this.html+=d.render();this.html+="</div>";break;case M.CENTER:this.html+="<h1>";this.html+=d.render();this.html+="</h1>";break;case M.RIGHT:this.html+='<div class="ui-btn-right">';this.html+=d.render();this.html+="</div>";break;default:M.Logger.log("ToolbarView children must have an anchorLocation of M.LEFT, M.CENTER, or M.RIGHT",M.WARN);return}}}},registerEvents:function(){this.backButton&&this.backButton.registerEvents();this.bindToCaller(this,M.View.registerEvents)()},
style:function(){var a="";if(this.cssClass)a+=' class="'+this.cssClass+'"';return a}});
M.FormView=M.View.extend({type:"M.FormView",showAlertDialogOnError:YES,alertTitle:"Validation Error(s)",validate:function(){var a=this.getIds(),b;for(b in a)M.ViewManager.getViewById(a[b]).validators||delete a[b];var c=YES;M.Validator.clearErrorBuffer();for(b in a){var d=M.ViewManager.getViewById(a[b]);d&&d.validators&&_.each(d.validators,function(e){e.validate(d,b)||(c=NO)})}c||this.showErrors();return c},showErrors:function(){var a="";_.each(M.Validator.validationErrors,function(b){var c=M.ViewManager.getViewById(b.errObj.viewId);
c&&c.cssClassOnError&&c.addCssClass(c.cssClassOnError);a+="<li>"+b.msg+"</li>"});this.showAlertDialogOnError&&M.DialogView.alert({title:this.alertTitle,message:a})},clearForm:function(){this.clearValues()},getFormValues:function(){return this.getValues()}});
M.TableView=M.View.extend({type:"M.TableView",removeContentRowsOnUpdate:YES,removeHeaderRowOnUpdate:NO,isInitialized:NO,header:null,render:function(){this.html+='<div id="'+this.id+'_container"><table id="'+this.id+'"'+this.style()+"><thead></thead><tbody></tbody></table></div>";return this.html},style:function(){var a=' class="tmp-table';if(this.cssClass)a+=" "+this.cssClass;a+='"';return a},theme:function(){this.header&&this.renderHeader()},renderHeader:function(){if(this.header&&this.header.data){if(this.header.cols&&
this.header.cols.length>0){html="<colgroup>";_.each(this.header.cols,function(a){html+='<col width="'+a+'">'});html+="</colgroup>";$("#"+this.id).prepend(html)}html="<tr>";_.each(this.header.data,function(a){html+='<th class="tmp-table-th">'+(a&&a.toString()?a.toString():"")+"</th> "});html+="</tr>";this.addRow(html,YES)}},renderUpdate:function(){var a,b=this.value;if(this.removeHeaderRowOnUpdate&&this.removeContentRowsOnUpdate)this.removeAllRows();else this.removeContentRowsOnUpdate&&this.removeContentRows();
if(b&&b.content&&b.content.length>0){if(b.header&&b.header.data){this.header=b.header;this.renderHeader()}if(b.content&&b.content.length>0){var c=this,d=0;_.each(b.content,function(e){d=d===0?1:0;a='<tr class="tmp-table-tr-'+(d===1?"a":"b")+'">';_.each(e,function(f){a+='<td class="tmp-table-td">'+(f&&f.toString()?f.toString():"")+"</td> "});a+="</tr>";c.addRow(a)})}}else M.Logger.log("The specified content binding for the table view ("+this.id+") is invalid!",M.WARN)},addRow:function(a,b){b?$("#"+
this.id+" thead").append(a):$("#"+this.id+" tbody").append(a)},removeAllRows:function(){$("#"+this.id).empty()},removeContentRows:function(){$("#m_3 tr td").parent().remove()}});
